nextstrain/nextclade

- packages/web/config/next/next.config.ts
This resolves bundling issues with Threads.js workers.
When `experimental.modern = true` in Next.js config, the application crashes in production, because worker modules canot be found.
We set `experimental.modern = false` to avoid this issue.
> fix: resolve Threads.js workers bundling error in production

- packages/web/config/nodemon/serve.json
- packages/web/infra/lambda-at-edge/modifyOutgoingHeaders.lambda.js
- packages/web/tools/server/server.ts
This modifies Lambda@Edge function to add cache-control headers to build artifacts in /_next directory. These are guaranteed to have different names on changes (due to appended hash string), so indefinite client-side caching is possible.
Also makes local server script to use the same headers.
> chore: add cache-control header for build artefacts in _next dir

- packages/web/infra/lambda-at-edge/modifyOutgoingHeaders.lambda.js
This modifies Lambda@Edge function to remove unnecessary permissions in content security policy (CSP).
> chore: make content security policy more strict

- packages/web/src/algorithms/run.ts
- packages/web/src/algorithms/types.ts
- packages/web/src/components/Main/MainPage.tsx
- packages/web/src/components/Main/UploadZone.tsx
- packages/web/src/components/Main/Uploader.tsx
- packages/web/src/components/Main/UploaderResultsStatus.tsx
- packages/web/src/components/Results/ResultsPage.tsx
- packages/web/src/components/Results/ResultsStatus.tsx
- packages/web/src/components/Results/ResultsTable.tsx
- packages/web/src/i18n/i18n.ts
- packages/web/src/state/algorithm/algorithm.actions.ts
- packages/web/src/state/algorithm/algorithm.reducer.ts
- packages/web/src/state/algorithm/algorithm.sagas.ts
- packages/web/src/state/algorithm/algorithm.selectors.ts
- packages/web/src/state/algorithm/algorithm.state.ts
This improves user experience by making interface faster, more interactive and by providing more visual feedback when different stages of the processing pipeline are running for every sequence.
> feat: progress indicators & better user experience

- packages/web/src/i18n/resources/es/common.json
Hi @ivan-aksamentov ! Based on the discussion about what 'back' refers to, I changed it to reflect the correct meaning.
Thank you again!
> Changed 'back' from espalda to volver

- packages/web/src/pages/_app.tsx
- packages/web/src/theme.ts
- packages/web/src/types/styled.d.ts
This passes a theme object though React context, such that styled components can use theme properties attached as props.
> feat: add styled-components theme

- packages/web/src/filtering/filterByQCIssues.ts
- packages/web/src/filtering/runFilters.ts
Due to a bug in filtering, the incomplete (not yet fully analyzed) sequences were not being shown in results table. This PR fixes that.
> fix: show sequences being analyzed again

- packages/web/src/components/Tree/FilterBadge.tsx
- packages/web/src/components/Tree/FilterBadges.tsx
Clicking on a filter badge temporarily disables the filter. Clicking again re-enables it.
The current implementation is somewhat naive and not robust in some of the cases cases. Upstream changes in Auspice are required for proper implementation to be possible.
> feat: add ability to disable filters temporarily

- packages/web/src/components/Results/ButtonTree.tsx
- packages/web/src/state/reducer.ts
- packages/web/src/state/store.ts
- packages/web/src/state/util/withReduxDevTools.ts
- packages/web/src/types/auspice/index.d.ts
- packages/web/src/types/auspice/src/reducers/controls.d.ts
- packages/web/src/types/auspice/src/reducers/entropy.d.ts
- packages/web/src/types/auspice/src/reducers/frequencies.d.ts
- packages/web/src/types/auspice/src/reducers/tree.d.ts
- packages/web/src/types/auspice/src/reducers/treeToo.d.ts
Contributes to #139 
This:
- filters parts of the state and actions from the serialization
- adjusts types so that filtering is somewhat typesafe (it is not perfect still, due to strange types in redux devtools package)
- avoids unnecessary payload on one of the click actions
> chore: make redux devtools faster

- packages/web/src/helpers/saveFile.ts
- packages/web/src/state/algorithm/algorithm.sagas.ts
Set correct mime types to exported blobs, so that browsers don't get confused and don't add .txt file extensions.
> fix: make sure exported files have correct extensions

- packages/web/src/cli/cli.ts
This fixes a bug, when `--input-tree` was erroneously ignored, due to parameter not being passed properly between functions, so that the custom input tree was not used.
> fix(cli): make sure the custom tree is used

- packages/web/src/components/Results/ResultsTable.tsx
Safari flexbox bug requires setting explicit height, otherwise our table has a height of 0 pixels.
Resolves #138
> fix: make sure results table is displayed correctly on Safari 13

- packages/web/src/algorithms/primers/validatePcrPrimers.ts
- packages/web/src/cli/cli.ts
- packages/web/src/io/validateGeneMap.ts
This adds new CLI parameters, for overriding the default clades, primers and gene map.
This now correctly resolves primer positions relative root sequence when a custom root sequence is provided.
> feat(cli): add possibility to override clades, primers and gene map

- packages/web/src/cli/cli.ts
The `--input-clades` parameters was not needed, because clades definitions are not used in the algorithm. Algorithm deduces clades from the tree. Clade definitions are only used in the web app to display clade-defining mutations.
> refactor: remove unused clade definitions from CLI interface

- packages/web/infra/lambda-at-edge/modifyOutgoingHeaders.lambda.js
- packages/web/public/.well-known/dnt-policy-1.0.txt
This attempts to reduce the effects of some of adblocking browser extensions on the app functionality. In particular here we:
- declare DNT:1 compliance (see https://www.eff.org/dnt-policy)
- correct the CSP for images embedded as `data:`
> feat: attempt to reduce breakage by adblockers

- packages/web/src/i18n/i18n.auspice.ts
- packages/web/src/i18n/i18n.ts
- packages/web/src/state/settings/settings.sagas.ts
- packages/web/src/state/settings/settings.state.ts
This adds a check when setting locale: if locale is not present, the default locale is set.
Unchecked, missing locale could come from autodetection or from local storage.
This also disables autodetection. Users should, hopefully, find the language switcher on top of the page if they need locale to be changed.
> fix: prevent app from crashing when a locale is missing

- packages/web/src/helpers/formatSnpCluster.ts
- packages/web/src/io/serializeResults.ts
SNP clusters were creating multiple rows when exported to CSV/TSV.
This fixes this problem by formatting the clusters such that they fit into 1 column and row.
> fix: format SNP clusters properly for export

- packages/web/src/cli/cli.ts
- packages/web/src/io/serializeResults.ts
Due to different characters present or not in nucleotide composition, it makes CSV/TSV column number and order uncertain and makes row concatenation much harder, so we remove it from CSV/TSV export here.
> feat: don't output nucleotide composition to CSV

- packages/web/src/io/serializeResults.ts
BREAKING CHANGE:
- qc.seqName is removed from CSV, TSV and JSON outputs (it had the same values as seqName)
- order of columns is changed in CSV ans TSV outputs
> feat: enforce csv column order, remove duplicate qc.seqName column

- packages/web/src/components/Tree/FilterBadges.tsx
- packages/web/src/helpers/removeUndefined.ts
Resolves #235
This was due to enable/disable callbacks (triggered on badge removal) were leaving object keys with `undefined` value. Subsequent iteration on these values would then cause a crash.
The type mismatch was somehow not caught by Typescript, probably due to lodash typings.
This PR adds removal of `undefined` values, as a last instruction in these callbacks.
> fix: avoid crash on filter badge removal

- packages/web/src/components/Common/SEO.tsx
- packages/web/src/initialize.ts
- packages/web/src/state/settings/settings.reducer.ts
- packages/web/src/state/settings/settings.selectors.ts
- packages/web/src/state/settings/settings.state.ts
This resets the locale key value in local storage for every user of the web app. This will force everybody to English on next page load.
Our localizations are incomplete and ugly (e.g. some text does not fit and goes beyond buttons etc.). Language autodetection has been removed a while ago. However, users' browsers still persist the language setting. This will reset it to English. And if they want, they will switch manually.
> feat: force reset all users to English locale

- packages/web/src/algorithms/defaults/sars-cov-2/rootSeq.ts
- packages/web/src/helpers/sanitizeRootSeq.ts
- packages/web/src/io/fetchInputsAndRunMaybe.ts
- packages/web/src/state/algorithm/algorithm.actions.ts
- packages/web/src/state/algorithm/algorithm.reducer.ts
This allows to provide custom root sequence and reference tree for the web app.
This PR adds processing for two new URL parameters: `input-root-seq` and `input-tree` (same names and functionality as in CLI)
When the application is loaded with one or both of these, as well as with `input-fasta` parameter, containing the URLs to corresponding files, instead of showing the main page, Nexclade will download these files and start analysis immediately, using the provided sequences, as well as the provided root sequence and/or reference tree.
Example URL (pointing to the default files hosted on GitHub):
> https://master.clades.nextsltrain.org/?input-fasta=https://raw.githubusercontent.com/nextstrain/nextclade/8767611a95b308ff33d26c73ff536fd999615e10/packages/web/src/algorithms/defaults/sars-cov-2 …
> feat: fetch input root sequence and input ref tree provided  URL params

- packages/web/src/algorithms/tree/treeFindNearestNodes.ts
this PR excludes all sites that are gapped in the reference node from distance calculations. We only compare substitutions in the query sequence to the reference node and having gaps contribute to the mutation count distorts the distance.
> fix: exclude gaps in reference node from distance calculations

- packages/web/src/components/Results/ButtonExport.tsx
- packages/web/src/components/Results/ButtonTree.tsx
- packages/web/src/components/Tree/TreeIcon.tsx
- packages/web/src/state/algorithm/algorithm.actions.ts
- packages/web/src/state/algorithm/algorithm.reducer.ts
- packages/web/src/state/algorithm/algorithm.sagas.ts
- packages/web/src/state/algorithm/algorithm.selectors.ts
- packages/web/src/state/algorithm/algorithm.state.ts
- packages/web/src/state/ui/ui.state.ts
- packages/web/src/state/util/withReduxDevTools.ts
This adds an entry to the export dropdown called "Export to Auspice", which allows to download the resulting tree with user-provided sequences placed on it (the same tree as on tree page). This can be stored and processed or visualized in https://auspice.us, for instance.
Warning: before interpreting this result file, it is important to understand the limitations of the Nextclade placement algorithm, as opposed to full phylogenetic analysis with main Nextstrain toolchain.
> feat: allow exporting Auspice tree json result again

- packages/cli/README.md
As pointed out in #252 the current beta package in npm is quite old (0.4.0) so minor change to the documentation to point to the alpha version as that will install the latest non-stable package.
> Update CLI readme to install latest alpha

- packages/web/src/algorithms/defaults/sars-cov-2/geneMap.ts
- packages/web/src/cli/cli.ts
- packages/web/src/io/getGeneMap.ts
Attempts to resolve #252
In CLI code path  we've been loading and trying to use the gene map JSON directly, while it requires some preprocessing first (which was first introduced in the web app). This PR adds the missing preprocessing step.
> fix(cli): add missing preprocessing step for custom gene maps in CLI

- packages/web/src/styles/auspice.scss
We've been missing a stylesheet from auspice for the entropy panel. This caused zoom overlay (triggered when holding <kbd>shift</kbd> or <kbd>alt</kbd> keys) to have an opaque black background, making the panel unusable.
This PR adds import for the missing stylesheet, this fixes this issue and probably many other small style-related issues with entropy panel.
> fix: remove black overlay above entropy panel when holding shift or alt

- .travis.yml
- tools/install-aws-cli
This is to make sure that we don't accumulate the old release artifacts
> chore: clear S3 bucket before deployment

- packages/web/src/styles/_theme.scss
Let's not allow buttons to shout at our users. We don't strictly following Material Design, or, pretty much, any design system anyway.
> feat: remove uppercase text transform from buttons

- packages/web/src/algorithms/nucleotideCodes.ts
- packages/web/src/algorithms/tree/treeFindNearestNodes.ts
- packages/web/src/algorithms/tree/treePreprocess.ts
- packages/web/src/algorithms/tree/types.ts
this might speed up placement a bit.
> perf: avoid re-filtering gaps from mutations for every node every time

- packages/web/babel.config.js
`@babel/plugin-transform-react-inline-elements` seems to be breaking MDX's ability to use custom components.
This PR disables that plugin. Hopefully temporarily.
See https://github.com/mdx-js/mdx/issues/1327
> fix: formatting markdown snippets (about and changelog)

- packages/web/src/algorithms/alignPairwise.ts
- packages/web/src/algorithms/parseSequences.ts
This fixes #285 by trimming leading and trailing Ns before aligning. 
This doesn't chance interpretation or behavior. We classify missing data left and right as "unsequenced". `N`s at the left or right end are essentially unsequenced.
> fix: trim leading and trailing to void seed matching problems

- packages/web/src/algorithms/tree/treeAttachNodes.ts
This PR fixes a problem of excess divergence in cases where there are gaps in the node we attach to. These gaps should not contribute to divergence.
> fix: avoid counting every gap in a new node as one divergence unit

- README.md
- packages/web/package.json
Windows was previously not supported due to hardcoding to a Unix-specific file. This provides an alternative that works. See https://github.com/nextstrain/nextclade/issues/313 https://github.com/hodcroftlab/covariants/issues/18 https://github.com/hodcroftlab/covariants/pull/71. Tested that I can run a dev server successfully with `npm dev:start_win`.
Fixes #313
> Add windows dev support

- conanfile.txt
- packages/nextalign/CMakeLists.txt
- packages/nextalign_cli/CMakeLists.txt
- packages/nextalign_cli/src/cli.cpp
- packages/nextalign_cli/src/filesystem.h
This switches nextalign CLI to use https://github.com/gulrak/filesystem as a drop-in replacement for `std::filesystem`.
Despite having C++17 enabled, there is a complication with Applce clang and macOS target version: we want to target older macOS versions (down to 10.12) which don't ship some of the features we need.
We solve the problem by using the replacement library.
There are also some minor formatting issues fixed.
> refactor: use ghc-filesystem as a replacement for std::filesystem

- packages/nextalign/benchmarks/src/AlignPairwise.benchmark.h
- packages/nextalign/benchmarks/src/Nextalign.benchmark.h
- packages/nextalign/benchmarks/src/main.cpp
- scripts/benchmarks.sh
This adjusts `make benchmarks` script for recent changes in the build system and moves `getData()` call from global scope into the benchmark class constructor
> chore: fix benchmarks [skip ci]

- packages/nextalign/benchmarks/src/AlignPairwise.benchmark.h
- packages/nextalign/benchmarks/src/Nextalign.benchmark.h
- packages/nextalign/benchmarks/src/utils/getData.h
Followup of #335
Fixes gene list being empty in benchmarks
> chore: fix list of genes being empty in benchmarks [skip ci]

- packages/nextalign_cli/src/cli.cpp
This adds `--out-of-order` CLI option which allows parallel processing out of order.
Without this flag the program will wait for results from the previous sequences to be written to the output files before writing the results of the next sequences. Due to variable sequence processing times, this might introduce unnecessary waiting times, but ensures that the resulting sequences are written in the same order as they occur in the inputs.
Specifying this flag allows to lift this requirement, which might make the processing faster, by eliminating waits, but might also lead to results written out of order. In this case, the order of results is not specified and depends on thread scheduling and processing times of individual sequences.
UPDATE: the logic has been inverted: out-of-order behavior …
> feat: add an option to allow out-of-order writes

- packages/nextalign_cli/src/cli.cpp
We were taking parent paths of named outputs and tried to create output directories from it.
When filename-only output flags were passed nextalign was crashing due to parent paths being empty.
This adds checks for empty paths to prevent that.
> fix: don't attempt to create directories from empty paths

- packages/web/infra/lambda-at-edge/modifyOutgoingHeaders.lambda.js
This was mistakenly removed in 8fe7158b39fafe3becaf0ec225f12c1c2f415eb8 and caused Nextclade data fetching to fail
> chore(infra): allow any host in connect-src csp

- packages/cli/package.json
The README documents >=12, and indeed on Node.js 10 the Nextclade CLI
doesn't work because worker_threads is not available.
> fix: Correct Node.js version requirement for the Nextclade CLI

- packages/nextalign/src/align/alignPairwise.cpp
This avoids crash in  seed extraction (`substr()`), when `seedCover` is negative. This can happen during gene alignment, for sequences with low-quality fragments. In this case we cannot proceed with alignment, so we bail out early.
> [nextalign] Prevent crashing when not enough good gene seed positions

- packages/nextalign/src/translate/translateGenes.cpp
query results are returned as alignment with insertions stripped, hence gap symbols in the reference should be stripped
> remove gaps from output of reference translations

- README.md
This is adding two new badges. An Anaconda badge pointing users to a conda package to install nextclade (and nextalign) and a Galaxy badge pointing users to use nextclade on the European Galaxy server. Nextalign is also packaged and available, but one badge is probably enough. There is also for both packages a BioContainer available (Docker/Singularity).
Greetings from Freiburg!
> add Conda and Galaxy badge

- packages/nextalign/src/nextalign.cpp
- packages/nextalign_cli/src/cli.cpp
Reference sequence was not included into output fasta file, eve with `--include-reference` flag, due to variable was not passed into returned object. 
Resolves #402
> fix: ensure ref sequence is included into outputs

- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/src/io/CsvWriter.cpp
- packages/nextclade_cli/src/cli.cpp
This PR rectifies contents of rows in CSV and TSV output files for sequences that trigger errors during processing.
For these rows, the `seqName` column now correctly contains sequence name, the `errors` column contains human-readable description of encountered error(s), and all other columns are empty (column delimiters are preserved).
> fix: correct content of csv/tsv rows when processing ends up with error

- packages/nextalign_cli/CMakeLists.txt
- packages/nextalign_cli/src/Logger.h
- packages/nextalign_cli/src/cli.cpp
- packages/nextclade_cli/CMakeLists.txt
- packages/nextclade_cli/src/Logger.h
- packages/nextclade_cli/src/cli.cpp
This PR introduces verbosity levels for Nextclade CLI and Nextalign CLI.
The amount of information printed to console can be changed using `--verbosity` flag. The following values are accepted (from least to most verbose):
- silent
- error
- warn
- info
- debug
Additionally, `--silent` flag is an alias for `--verbosity=silent` and `--vebose` is an alias for `--verbosity=info`. 
The "silent" verbosity level guarantees that no console output is produced. This is handy when using `stdout` as output stream, e.g. with `--output-fasta /dev/stdout`, to avoid performance-costly file IO when "piping" output of Nextclade or Nextalign into the next stage of the processing pipeline which accepts inputs on `stdin`. 
Additionally, the messages of `warning` verbosity (all warnings, including the ones …
> Implement cli verbosity levels, print warnings to stderr

- packages/nextclade/src/io/serializeResults.cpp
This fixes values of `rootOligonuc` and `primerOligonuc` in detected PCR primer changes in Nextclade's JSON output file. They now correctly contain oligonucleotide sequences in ATGC alphabet, not in internal representation.
> fix: properly serialize nucleotide sequences in primer results

- packages/nextalign/benchmarks/src/utils/getData.h
- packages/nextalign/include/nextalign/nextalign.h
- packages/nextalign/src/io/parseSequences.cpp
- packages/nextalign/tests/parseSequences.test.cpp
- packages/nextalign_cli/src/Logger.h
- packages/nextalign_cli/src/cli.cpp
- packages/nextclade/src/__tests__/findPrivateMutations.test.cpp
- packages/nextclade_cli/src/Logger.h
- packages/nextclade_cli/src/cli.cpp
This improves console logging messages of Nextclade CLi and Nextalign CLI.
The messages are not prefixed with message's log level (verbosity level) and the name of the application. Some of the error and warning messages have been reworded to better convey their meaning (but there are still some work to do here).
This should improve log readability and facilitate debugging when using Nextclade CLi and Nextalign CLI in complex pipelines.
Examples:
> [ WARN] Nextclade: Warning: in sequence "USA/UT-01231/2020": When processing gene "ORF7b": Unable to align: no seed matches. Note that this gene will not be included in the results of the sequence
> [ERROR] Nextclade: Error: when running the internal parallel pipeline: When parsing input sequences: Input stream ("path/to/an_empty_file.fasta") is …
> feat: improve cli console logging

- packages/web/src/components/Results/ResultsTable.tsx
This attempts to improve readability of the "Clade" colnum in Nextclade web:
- Increase width of the "Clade" column
- Left-align clade names in "Clade" column
The longest versioned clade seem to be "20J (Gamma, V3)" currently and I made clade column to be 120px wide, so that even "22W (Omicron, V25)" fits if it ever happen to exist (please don't)
Before:
After:
Longer:
> Improve "clade" column

- packages/nextclade/CMakeLists.txt
- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/src/analyze/findNucChanges.cpp
- packages/nextclade/src/analyze/findNucChanges.h
- packages/nextclade/src/analyze/getAminoacidChanges.cpp
- packages/nextclade/src/analyze/getAminoacidChanges.h
- packages/nextclade/src/analyze/linkNucAndAaChangesInPlace.cpp
- packages/nextclade/src/analyze/linkNucAndAaChangesInPlace.h
- packages/nextclade/src/io/serializeResults.cpp
- packages/nextclade/src/nextclade.cpp
- packages/nextclade/src/utils/range.h
- packages/web/src/algorithms/types.ts
- packages/web/src/components/SequenceView/ListOfAminoacidDeletions.tsx
- packages/web/src/components/SequenceView/ListOfAminoacidSubstitutions.tsx
- packages/web/src/components/SequenceView/PeptideContext.tsx
- packages/web/src/components/SequenceView/PeptideMarkerMutationGroup.tsx
- packages/web/src/components/SequenceView/SequenceMarkerGap.tsx
- packages/web/src/components/SequenceView/SequenceMarkerMissingEnds.tsx
- packages/web/src/components/SequenceView/SequenceMarkerMutation.tsx
- packages/web/src/components/SequenceView/groupAdjacentAminoacidChanges.ts
Here we establish a many-to-many relation between aminoacid changes (substitutions, deletions) and nucleotide changes (substitutions, deletions).
We group changes by positions:
- nucleotide substitution is related to aminoacid change iff nucleotide position is within the codon nucleotide range of that aminoacid
- nucleotide deletion is related to aminoacid change iff nucleotide deletion range intersects the codon nucleotide range of that aminoacid
We only state the fact of spatial locality of these changes and we say nothing about the causal relations between nucleotide changes and aminoacid changes, as this can not always be easily deduced from sequences only.
This data is automatically propagated to JSON result output and to the web app.
Here is what it looks like in the app:
In …
> Link aminoacid and nucleotide changes by position

- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/src/io/parseAnalysisResults.cpp
- packages/nextclade/src/io/serializeResults.cpp
- packages/nextclade_wasm/src/main.cpp
- packages/web/src/io/serializeResults.ts
- packages/web/src/state/algorithm/algorithmExport.sagas.ts
- packages/web/src/state/algorithm/algorithmRun.sagas.ts
- packages/web/src/workers/run.ts
- packages/web/src/workers/worker.serializeToCsv.ts
Resolves #395
This transforms root of the JSON output file (`nextclade.json`) from array to object.
The old array of results is now at `results` property.
Timestamp of the run, schema and Nextclade version are added as properties of the root object. This should help extending the format of this file in the future
Related #212
> BREAKING CHANGE Wrap results json in an object, add properties

- packages/nextalign/include/nextalign/nextalign.h
- packages/nextalign/include/nextalign/private/nextalign_private.h
- packages/nextalign/src/nextalign.cpp
- packages/nextalign/src/translate/translateGenes.cpp
- packages/nextalign/src/translate/translateGenes.h
- packages/nextclade/CMakeLists.txt
- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/src/io/serializeResults.cpp
- packages/nextclade/src/utils/concat.h
- packages/nextclade/src/utils/concat_move.h
- packages/nextclade_wasm/src/main.cpp
- packages/web/src/algorithms/types.ts
- packages/web/src/components/Results/ColumnName.tsx
- packages/web/src/components/Results/ResultsTable.tsx
- packages/web/src/components/SequenceView/PeptideView.tsx
- packages/web/src/state/algorithm/algorithm.reducer.ts
- packages/web/src/state/algorithm/algorithm.state.ts
- packages/web/src/workers/worker.analyze.ts
Previously a blank row was being displayed in sequence view for a gene, when that gene was missing, for example due to failed translation. 
It was hard to distinguish genes with no mutations and failed genes.
This adds:
- row coloring - dark grey
- a message that the gene is missing
- a tooltip with reasons of why that gene might be missing 
Resolves: https://github.com/nextstrain/nextclade/issues/441
> Display warnings when a gene is missing in sequence view

- packages/nextclade_wasm/src/main.cpp
- packages/web/src/components/Results/ExportDialogButton.tsx
- packages/web/src/state/algorithm/algorithm.actions.ts
- packages/web/src/state/algorithm/algorithm.state.ts
- packages/web/src/state/algorithm/algorithmExport.sagas.ts
- packages/web/src/workers/run.ts
- packages/web/src/workers/worker.serializeInsertionsToCsv.ts
This adds CSV file with stripped insertions to Nextclade web app "Download" dialog.
This is the same file as produced by Nextclade CLI and Nextalign CLI with `--output-insertions` flag.
This fils is also added into the "Download all" zip archive.
> Add insertions CSV file to download dialog

- packages/nextalign_cli/src/cli.cpp
- packages/nextclade_cli/src/cli.cpp
- packages/web/src/components/Results/ExportDialogButton.tsx
- packages/web/src/state/algorithm/algorithm.actions.ts
- packages/web/src/state/algorithm/algorithm.selectors.ts
- packages/web/src/state/algorithm/algorithm.state.ts
- packages/web/src/state/algorithm/algorithmExport.sagas.ts
Resolves #436 
The errors CSV file contains errors, warnings and names of failed genes for each sequence.
This PR adds this to the "base" CLI output (files written to the default path with the default name, similar to gene fasta) and also the `--output-errors` flag to change the default path, for both Nextclade CLI and Nextalign CLI.
It also adds the same file to the "Downloads" dialog in the web app, as a standalone file and included into the zip archive.
> Add output errors CSV file

- packages/web/src/components/Common/TableSlim.tsx
- packages/web/src/components/Results/ColumnInsertions.tsx
- packages/web/src/components/Results/HelpTips/HelpTipsColumnInsertions.mdx
- packages/web/src/components/Results/ListOfInsertions.tsx
- packages/web/src/components/Results/ResultsTable.tsx
- packages/web/src/helpers/sortResults.ts
This adds "Ins." column, for "Insertions". It simply exposes in the UI the data that we already had.
Row tooltip:
Help tooltip for the column:
> feat: add insertions column into results table

- packages/web/src/helpers/formatRange.ts
This fixes the off-by-one error in `formatRange()` (typescript version).
It touches quite a few places in the web app:
[The C++ version](https://github.com/nextstrain/nextclade/blob/fdb6a7acd5bd5fffbac68d327f0eb963a8d0bc3d/packages/nextclade/src/io/formatMutation.cpp#L10-L19) is correct.
> Fix range formatting for display in web app

- conanfile.txt
- conanfile.wasm.txt
- data/sars-cov-2/qc.json
- packages/nextclade/CMakeLists.txt
- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/src/io/parseQcConfig.cpp
- packages/nextclade/src/io/serializeQcConfig.cpp
- packages/nextclade/src/qc/isQcConfigVersionRecent.cpp
- packages/nextclade/src/qc/isQcConfigVersionRecent.h
- packages/nextclade_cli/src/cli.cpp
- packages/web/src/algorithms/types.ts
The `qc.json` is now versioned (with `"schemaVersion"` field), checks are made optional where possible, and warning is emitted is JSON is older than Nextclade. Here are the most important cases:
- It will crash if at least one required field is missing ("knownStopCodons" in this case):
```json5
{
"stopCodons": { "enabled": true }
}
```
The error message is:
> [ERROR] Nextclade: Error: When parsing QC configuration file: key "/stopCodons/knownStopCodons" is missing
- These are valid. The check won't run.
```json5
{
// nothing
}
{
"stopCodons": {}
}
{
"stopCodons": { "enabled": false }
}
```
- The only way to enable a check is to have `"enabled": true` and all of the required params present and have valid values:
```json5
{
"stopCodons": { "enabled": true, "knownStopCodons": [] }
}
{ …
```
> Version QC config JSON file

- data/sars-cov-2/qc.json
Adds `ORF8:68*` to the ignore list of misplaced stop codons for the "Stop codon" QC rule.
> Ignore stop codon ORF8:68*

- packages/nextclade/src/io/CsvWriter.cpp
This PR corrects a few issues with CSV results output:
- escape quitation marks
- surround with quotes when there are special characters
- use CRLF line endings for better compatibility and consistency with Nextclade 0.x
Also prevents column shift in CSV/TSV results when some of the QC checks are disabled by simply writing empty strings for every missing column.
> Correct CSV output file format

- packages/nextclade/src/qc/ruleFrameShifts.cpp
- packages/nextclade/src/qc/ruleStopCodons.cpp
Previously, for frame shifts and stop codons QC rules, the score assigned was:
- 0 is no detected
- 100 if at least 1 detected
This PR changes score to be `n * 75`, where `n` is number of detections
> feat: adjust QC scores for frame shits and stop codons

- scripts/build_locally.sh
- scripts/build_on_vercel.sh
Vercel build was broken since we moved to C++ and WASM. Other CIs use Docker for wasm build, but Vecel does not allow to run Docker containers (a branch with my attempts: [abandoned/chore/vercel-docker](https://github.com/nextstrain/nextclade/tree/abandoned/chore/vercel-docker))
This PR runs WASM and web build on Vercel's VM, which seems to be using Amazon Linux 2 distro. This setup assumes it runs on Amazon Linux 2 and if Vercel changes this one day, then everything will break.
Several hacks were implemented, in particular for Python SQLIte support, which is required for Conan.
> Fix vercel build

- packages/web/src/components/Layout/LayoutResults.tsx
- packages/web/src/components/Results/ResultsPage.tsx
- packages/web/src/components/Tree/TreePage.tsx
Here we apply `flex-basis: 100%` in a few places, because older versions of Safari (< 14) do not apply correct height in column-based flex layouts the compound syntax is used (e.g. `flex: 1 0 100%` results in zero height) or if omitted.
> fix: results table and tree layout in safari

- packages/nextclade/src/tree/Tree.cpp
Here we remove assumption that the `meta.colorings[].scale` property is present on colorings of `type` `categorical`. We are also checking if the `scale` is an array, before attempting to push new values into it.
This change should make Nextclade more robust to some of the input tree files.
Only the colorings with keys`region`, `country` and `division` are affected.
> fix: avoid crash when the `scale` property is missing in a tree coloring

- packages/nextclade/src/tree/treeAttachNodes.cpp
This simplifies the dialog to avoid duplicated and poorly formatted information.
Note that this affects the output tree JSON.
> feat: simplify tree node info dialog

- packages/nextclade/src/qc/ruleSnpClusters.cpp
Looks like the code assumed that the positions of mutations in clusters were sorted ascending and took cluster range boundaries as first and last positions.
https://github.com/nextstrain/nextclade/blob/392a741176cefe5defeff54675240c876c95f105/packages/nextclade/src/qc/ruleSnpClusters.cpp#L54-L55
But mutation positions were not sorted. This lead to incorrect ranges, sometimes with wrong, sometimes with inverted boundaries.
This PR adds sorting to mitigate that.
> fix: incorrect snp cluster ranges

- docs/conf.py
It was already in the environment for docs here but not being specified in the conf.py file. @ivan-aksamentov let me know if you'd like to petition for any of the options you specified which aren't in https://github.com/nextstrain/sphinx-theme to be included in it.
> use nextstrain-sphinx-theme in nextclade docs

- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/src/io/serializeResults.cpp
- packages/nextclade/src/nextclade.cpp
- packages/nextclade/src/qc/isQcConfigVersionRecent.cpp
- packages/nextclade_cli/src/cli.cpp
Currently Nextclade expects QC config `schemaVersion` to match Nextclade version itself. This means QC `schemaVersion` needs to be updated on every release.
This is no longer convenient now that we will be transitioning to the separate datasets repo. So instead we freeze the QC `schemaVersion` on a particular semver string hardcoded in Nextclade code.
Analysis results JSON `schemaVersion` was also refactored to bring the two versions closer together, even though Analysis results JSON `schemaVersion` is only used to write results and not checked or read anywhere for now.
> fix: ensure there are no false QC schema version warnings

- docs/user/nextclade-web.md
- packages/web/src/components/Main/DatasetSelector.tsx
- packages/web/src/components/Main/DatasetSelectorDropdown.tsx
- packages/web/src/helpers/useAxiosQuery.ts
- packages/web/src/initialize.ts
- packages/web/src/io/axiosFetch.ts
- packages/web/src/io/fetchDatasets.ts
- packages/web/src/io/fetchDatasetsIndex.ts
- packages/web/src/io/fetchInputsAndRunMaybe.ts
- packages/web/src/pages/_app.tsx
- packages/web/src/state/algorithm/algorithm.actions.ts
- packages/web/src/state/algorithm/algorithm.reducer.ts
- packages/web/src/state/algorithm/algorithm.selectors.ts
- packages/web/src/state/algorithm/algorithm.state.ts
- packages/web/src/state/algorithm/algorithmRun.sagas.ts
This adds the following URL parameters related to datasets:
- dataset-name
- dataset-reference
- dataset-tag
Additionally, the missing input file params were also added, so the full set is now:
- input-fasta
- input-root-seq
- input-tree
- input-pcr-primers
- input-qc-config
- input-gene-map
Due to complex iterations between datasets, various file input methods and ways of launching the analysis, a few things had to be moved:
- datasets state was moved from the dataset selector component into redux store
- datasets fetching logic was moved from the dataset selector component to the initialization stage (a side effect in the App component)
- dataset selector component is now stateless
For the future: it is important that datasets are fetched and one of them is selected (either default, …
> feat: add dataset-related URL parameters

- packages/web/src/helpers/parseUrl.ts
- packages/web/src/io/fetchDatasets.ts
- packages/web/src/io/fetchInputsAndRunMaybe.ts
- packages/web/src/pages/_app.tsx
It could often happen that due to props changes of the Next.js's App component, the steps that should only run once could run multiple times. This caused strange bugs, like app state randomly changing on page navigation or state first loaded correctly, but then reset to an unexpected value.
This PR ensures that the application initialization steps run only once.
These currently are:
- prefetching pages
- initializing Redux store
- initializing persistence (local storage)
- fetching, parsing and saving dataset index in the Redux store
- parsing URL params
- fetching input files from URL params
Previously some or all of these steps could have ran multiple times. But now they are guaranteed to run to successful completion only once (but can be repeated if failed).
Additionally, Next.js would …
> fix(web): run init only once

- packages/web/src/algorithms/types.ts
- packages/web/src/components/SequenceView/ListOfAminoacidDeletions.tsx
- packages/web/src/components/SequenceView/ListOfAminoacidSubstitutions.tsx
- packages/web/src/components/SequenceView/sortByGenes.ts
- packages/web/src/state/algorithm/algorithmRun.sagas.ts
Corresponding change in data: https://github.com/nextstrain/nextclade_data/pull/9
This helps to visualize gene-related data better, according to practical needs.
> feat: use default dataset gene and gene order preference

- packages/web/src/components/Results/HelpTips/HelpTipsColumnClade.mdx
It does not make sense to have it there when analyzing other pathogens.
> fix: remove SARS-CoV-2 clade schema from the clade column tooltip

- packages/nextalign/src/translate/translateGenes.cpp
This is an attempt to fix peptide translations in frame-shifted regions.
Based on #533.
> Detect frame shifts (with masking)

- packages/web/src/components/Results/HelpTips/HelpTipsColumnGaps.mdx
- packages/web/src/components/Results/HelpTips/HelpTipsColumnInsertions.mdx
- packages/web/src/components/Results/HelpTips/HelpTipsColumnMut.mdx
Now that we have more pathogens, references to SARS-CoV-2 specifics no longer make sense.
> fix: remove mentions of Wuhan-Hu-1 in tooltips

- packages/web/src/components/Results/ColumnNameTooltip.tsx
The tooltip for "Sequence name"  column of the results table is sometimes too wide, making the table columns inside look disconnected and harder to read. This happens when sequence names are very long.
This PR limits the width of the tooltip, such that the table looks pretty regardless of sequence name length. The sequence name is now forced to wrap to multiple lines if too long.
> feat(web): limit width of the summary tooltip

- packages/nextclade_wasm/src/main.cpp
After #504 when translation past stop codons became optional, Nextalign and Nextclade CLI gained their flags to toggle this option. However, Nextclade Web was incorrectly using the default value, and translation was terminated on the first stop. 
This fixes the option's value so that Nextclade Web translates full peptides as expected.
This also solves the problem of gigantic peptide context tooltips, caused by deletions that appear in peptides context due to padding with `-` after translation stops. This kind of situations is additionally mitigated in #544.
> fix: translate past first stop codon in nextclade web

- packages/web/src/components/SequenceView/PeptideContext.tsx
- packages/web/src/components/SequenceView/PeptideMarkerMutationGroup.tsx
Currently when a large group of consecutive mutations or deletions appear in a peptide, mouse hovering this group displays a tooltip which may not fit to the screen due to both the width of the peptide context table and height of the list of mutations and deletions.
This PR truncates the context table and the lists, both in the middle, keeping the edges, all making sure tooltips are not too large and that they fit to the screen nicely.
Large tooltips previously appeared due to a bug fixed in https://github.com/nextstrain/nextclade/pull/543, but we should still truncate for the cases where large groups of mutations or deletions appear in user-provided sequences due to various reasons.
> feat(web): truncate peptide context and list of changes in tooltips

- packages/web/src/components/Results/ColumnFrameShifts.tsx
- packages/web/src/components/Results/ColumnStopCodons.tsx
- packages/web/src/components/Results/HelpTips/HelpTipsColumnFrameShifts.mdx
- packages/web/src/components/Results/HelpTips/HelpTipsColumnStopCodons.mdx
The notation now uses parentheses: first number is a number of unexpected changes and the second is total (unexpected+known). Help tips are adjusted to explain this.
> feat(web): better frame shifts and stop codons columns

- README.md
Adds JOSS badge to README
Looks like this:
> chore: add JOSS badge to README

- packages/nextalign/include/nextalign/nextalign.h
- packages/nextalign/include/nextalign/private/nextalign_private.h
- packages/nextalign/src/translate/detectFrameShifts.cpp
- packages/nextalign/src/translate/detectFrameShifts.h
- packages/nextalign/src/translate/extractGene.cpp
- packages/nextalign/src/translate/extractGene.h
- packages/nextalign/src/translate/mapCoordinates.cpp
- packages/nextalign/src/translate/mapCoordinates.h
- packages/nextalign/src/translate/translateGenes.cpp
- packages/nextalign/src/utils/at.h
- packages/nextalign/tests/CMakeLists.txt
- packages/nextalign/tests/extractGene.test.cpp
- packages/nextalign/tests/findMask.test.cpp
- packages/nextalign/tests/mapCoordinates.test.cpp
- packages/nextalign/tests/range.test.cpp
- packages/nextalign/tests/translateGenes.test.cpp
- packages/nextclade/src/io/parseAnalysisResults.cpp
- packages/nextclade/src/io/serializeResults.cpp
- packages/web/src/algorithms/types.ts
- packages/web/src/components/Common/TableSlim.tsx
- packages/web/src/components/SequenceView/PeptideMarkerFrameShift.tsx
- packages/web/src/components/SequenceView/SequenceMarkerFrameShift.tsx
- packages/web/src/helpers/formatRange.ts
In this PR for every frame shift we find:
- (A) position of the beginning of the immediately preceding adjacent nuc deletion 
- (B) position of the end of the immediately following adjacent nuc deletion 
We extend codon masking of the aligned peptide to cover the range A to B, which might be wider than the range of the frame shift.
We also obtain the 2 ranges:
- leading: from (A) to frame shift begin
- trailing: from frame shift end to (B)
(in codon coordinates)
These ranges are now being written into results JSON and displayed in the Web UI:
> fix: mask codons containing nuc deletions before and after frame shift

- packages/nextalign/src/align/alignPairwise.cpp
Fixes comment typos to what I think was meant
> fix: typo in comments in alignPairwise.cpp

- packages/nextclade/src/qc/rulePrivateMutations.cpp
After #564 the "Private mutations" QC check was incorrectly counting individual deletions, rather than contiguous ranges. This is due to difference in `struct`s of private and non-private deletions (individual vs ranges). This resulted in QC score being too high for sequences that have many deletions.
This PR adds:
[x] find contiguous ranges of private deletions
[x] count them and use this count  rather than array size
This should now bring the "Private mutations" QC score back to what was before #564.
> Count private del ranges instead of individual dels in qc

- packages/web/src/algorithms/types.ts
- packages/web/src/io/fetchInputsAndRunMaybe.ts
- packages/web/src/state/algorithm/algorithm.actions.ts
- packages/web/src/state/algorithm/algorithm.reducer.ts
- packages/web/src/state/algorithm/algorithm.selectors.ts
- packages/web/src/state/algorithm/algorithm.state.ts
- packages/web/src/state/algorithm/algorithmRun.sagas.ts
When datasets feature was added, a data race was introduced due to lack of synchronization between asynchronous data fetching from locations provided by URL params and reading this data before launching the algorithm.
The order of operations was as follows:
1. Retrieve URLs from URL params
2. Start fetching from these urls (asynchronously)
3. Save fetched data in redux store upon arrival
4. Read data from redux store. If it's empty, load default data from a dataset.
5. Do some other, unrelated operations.
6. Launch the algorithm.
However, step 4 was not waiting until step 3 is completed. So it could happen that the data read would yield and empty result, because fetching was still in progress. When that happened, algorithm would start with the default data, even though URL params are …
> fix: avoid race between data fetch and read when url params are used

- packages/nextalign/src/translate/mapCoordinates.cpp
- packages/nextalign_cli/src/cli.cpp
- packages/nextclade/src/analyze/findNucChanges.cpp
- packages/nextclade/src/analyze/getAminoacidChanges.cpp
- packages/nextclade/src/io/CsvWriter.cpp
- packages/nextclade/src/io/parseAnalysisResults.cpp
- packages/nextclade_cli/src/io/format.h
- packages/nextclade_cli/src/main.cpp
- packages/nextclade_common/include/nextclade_common/datasets.h
- packages/web/src/algorithms/types.ts
- packages/web/src/components/Data/DataPage.tsx
This PR aims to clean up the C++ parts of the codebase a little, but fixing compiler warnings and removing unused code. There should be no change of the behavior.
> refractor: cleanup

- packages/nextalign/src/translate/mapCoordinates.cpp
This was manifesting as a crash in macOS. Like all memory bugs, it was hard to reproduce, but @corneliusroemer eventually found that it was crashing in the `CoordinateMapper` constructor. After some long staring into the code I found an unguarded access to an empty array.
> fix: segfault in coordinate mapper due to out-of-bounds array access

- packages/nextalign/src/align/alignmentParams.cpp
- packages/nextalign/tests/alignmentParams.test.cpp
This improves calculation of bandwidth and shift for peptide alignment, previously introduced in https://github.com/nextstrain/nextclade/pull/613
In this version we ensure that the sequences with large insertions (large number of ref gaps) get a large enough band width.
> feat: tune params to improve peptide alignment

- packages/nextalign/src/align/alignPairwise.cpp
handle cases when the relative shift of query and reference is larger than the query
@ivan-aksamentov: please have a look. I'll test this on the cluster as well.
> fix crash when relative shift (bandwidth) is larger than query length

- packages/nextclade/src/qc/rulePrivateMutations.cpp
If there is no open range by the end of the loop, then `begin` might be `nullopt`. Then it's illegal to dereference it in the body of this conditional. I add an additional check to see if `begin` contains a value.
And while we are here, why don't we also check if the range is not empty before pushing it, as well as clarify a couple of comments? (The rule of boy scouts: Always leave the campground cleaner than you found it)
> fix: avoid potential dereference of nullopt

- packages/web/src/workers/run.ts
On a busy computer/browser Nextclade Web sometimes crashes with a webworker timeout message.
This is due to either webworker or the main thread being busy for an extended period of time, leading to communication delays between them. This can happen if a large set of sequences is analyzed on an underpowered machine, or on a machine with most of the resources (CPU, RAM) already occupied by other  browser tabs and processes.
Additionally, the wasm modules for workers are lazy-loaded from the server, so if there are network problems or if network is too slow, the initialization of a new worker, might be additionally delayed by the network overhead. In particular, after fresh releases, when these modules are not yet in the browser's cache.
In rare cases, when there are bugs in the C++ code of …
> fix: reduce number of webworker timeout errors

- packages/nextalign/include/nextalign/nextalign.h
- packages/nextalign/src/align/alignPairwise.cpp
- packages/nextalign/src/align/alignPairwise.h
- packages/nextalign/src/options/options.cpp
- packages/nextalign/src/translate/translateGenes.cpp
- packages/nextalign/tests/alignPairwiseWithCodons.test.cpp
- packages/nextalign_cli/src/cli.cpp
- packages/nextclade_cli/cli.json
- packages/nextclade_cli/src/io/getNextalignOptions.h
- packages/nextclade_cli/src/main.cpp
Since https://github.com/nextstrain/nextclade/pull/613 aminoacid seed alignment parameters and flags are unused. This PR removes them.
BREAKING CHANGE: the family of CLI flags `--seed-aa-*` has been removed from the CLI interface. Migration path: remove these flags from Nextalign and Nextclade CLI invocation.
> fix: remove unused aa seed parameters

- packages/nextclade/src/tree/treePreprocess.cpp
When `--genes` flag was provided to Nextclade CLI, which contains a list with only a subset of genes present in gene map, it would result in an error "Reference peptide not found".
This was caused by the incorrect assumption in this part of code, that all ref genes are always present, which is not the case when genes are excluded with some of the genes omitted in the `--genes` flag.
Here  I made it so that if a reference peptide is not found, we now simply continue iterating, ignoring that gene.
> fix: error when `--genes` flag contains a subset of genes

- packages/nextalign/src/align/alignPairwise.cpp
Followup to https://github.com/nextstrain/nextclade/pull/630.
I forgot to remove the parameters that don't exist anymore from debug trace statement.
> fix: remove non-existent parameters from debug trace statement

- packages/nextalign/include/nextalign/nextalign.h
- packages/nextalign/include/nextalign/private/nextalign_private.h
- packages/nextalign/src/nextalign.cpp
- packages/nextalign/src/strip/stripInsertions.h
- packages/nextalign/tests/stripInsertions.test.cpp
- packages/nextalign_cli/CMakeLists.txt
- packages/nextalign_cli/src/cli.cpp
- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/src/__tests__/findNucChanges.test.cpp
- packages/nextclade/src/io/formatMutation.cpp
- packages/nextclade/src/io/formatMutation.h
- packages/nextclade_wasm/src/main.cpp
- packages/web/src/components/Results/ListOfInsertions.tsx
Multiple related defects were identified:
1. The `pos` field in the internal objects representing insertions was of by one. `1` needed to be subtracted in insertion detection code to adjust for the fact that `pos` represents a position in reference ***\*after\**** which the insertion occurred. But it did not.
2. The formatting in the results table in Nextclade Web was incorrectly not converting insertion positions to 1-based, which resulted in off-by-one in the opposite direction, "compensating" the mistake
3. Nextalign erroneously used a duplicated implementation of the formatting function different from the one in (3) that erroneously did not convert position to 1-based, similar to (2), so the mistake in (1) was not manifesting in insertions CSV file and manifesting in JSON results …
> fix: off-by-one errors in insertion positions

- packages/web/src/components/GeneMap/GeneMapTable.tsx
- packages/web/src/components/Layout/LayoutMain.tsx
- packages/web/src/components/Layout/LayoutResults.tsx
- packages/web/src/components/Results/ResultsPage.tsx
- packages/web/src/components/Results/ResultsTable.tsx
- packages/web/src/components/Results/Tooltip.tsx
- packages/web/src/components/Tree/TreePage.tsx
- packages/web/src/styles/components/Results.scss
This removes limitations on width of the container that is used in `/results` and `/tree` pages of Nextclade Web. This allows for more space to be occupied by useful information, like the sequence views and the phylo tree, at least on larger screens. 
The layout of the results page is quite complex, so there might be some strange side-effects on smaller screens, especially mobile. But I checked on our main target desktop sizes: 720p, 1080p, 1440p and 4k and it looks good so far.
> feat: make results and tree pages full width

- packages/nextalign/include/nextalign/nextalign.h
- packages/nextalign/src/translate/extractGene.cpp
- packages/nextalign/src/translate/mapCoordinates.cpp
This accounts for the fact that the ranges are half-one on the right. So dereferencing `end` index overflows the buffer.
> fix: prevent buffer overflow in coord map

- scripts/build_on_vercel.sh
There seems to be now Python 3.9 in the Vercel VM and, similarly to the default Python on RHEL 7, it does not contain sqlite built-in module (which should be enabled when Python binaries are built), so `conan` fails with:
```
- Create conan profile 	
Traceback (most recent call last):
File "/usr/local/bin/conan", line 33, in <module>
sys.exit(load_entry_point('conan==1.43.0', 'console_scripts', 'conan')())
File "/usr/local/bin/conan", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/local/lib/python3.9/importlib/metadata.py", line 77, in load
module = import_module(match.group('module'))
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen …
```
> chore(ci): fix Vercel builds

- CMakeLists.txt
- packages/common/CMakeLists.txt
- packages/common/README.md
- packages/common/include/common/config.h
- packages/common/include/common/contract.h
- packages/common/include/common/debugbreak.h
- packages/common/include/common/ieee754_comparison.h
- packages/common/include/common/macro_overload.h
- packages/common/src/common.cpp
- packages/nextalign/CMakeLists.txt
- packages/nextalign_cli/CMakeLists.txt
- packages/nextclade/CMakeLists.txt
- packages/nextclade_cli/CMakeLists.txt
- packages/nextclade_json/CMakeLists.txt
- packages/nextclade_wasm/CMakeLists.txt
As a part of cleanup efforts, let's introduce another package called "common".
This package will contain the functionality shared across all other packages. This will be mostly very generic and lightweight things, like small utilities and extensions to standard library. This package should not get any large dependencies.
This package is different from nextclade_common, which contains specific functionality, like datasets download, only used in nextclade and nextclade_wasm. We don't want to burden other packages with heavy dependencies, hence the new package.
Future work: we need to carefully pick the duplicated functionality and replace it with includes to this package.
> refactor: introduce package "common"

- packages/common/CMakeLists.txt
- packages/common/include/common/safe_vector.h
This class wraps std::vector and adds some invariant checks to catch array access errors in debug mode. This will allow to remove some of the external checks scattered across the codebase.
> refactor: add safe_vector class

- packages/common/CMakeLists.txt
- packages/common/include/common/safe_string.h
- packages/common/include/common/safe_string_view.h
- packages/nextalign/include/nextalign/nextalign.h
- packages/nextalign/src/alphabet/aminoacids.cpp
- packages/nextalign/src/alphabet/nucleotides.cpp
- packages/nextalign/src/translate/decode.cpp
- packages/nextalign/src/translate/extractGene.cpp
- packages/nextalign/src/utils/map.h
Simlarly to https://github.com/nextstrain/nextclade/pull/671, adds wrappers for string classes. Only used for sequence data.
> refactor: use safe_string and safe_string_view

- packages/nextclade/src/tree/Tree.cpp
**HOTFIX** goes directly to staging and release, to bypass unreleased master. Reason: urgent fix for a 100% guaranteed crash in production Nextclade CLI.
In case where the key is not present the const version of the get function:
```
const json& get(...) const
```
was returning `defaultValue` which is a reference to a temporary, and hence was destroyed after return, thus the returned reference was dangling.
Here I remove the get function, and move conditionals to the caller. I also simplify the chained access with a json pointer.
> fix: undefined behavior in tree json acccess

- packages/nextclade/src/analyze/findNucleotideRanges.cpp
In the inner loop we check for `i < length` but then `i++` and then access the array with this `i` . So it read at least 1 character after the end.
I modified this loop to not go off by 1 and also simplified it.
Before:
https://github.com/nextstrain/nextclade/blob/7e48d224b6c4782f48b8347201c1355430b0a4f1/packages/nextclade/src/analyze/findNucleotideRanges.cpp#L34-L39
After:
https://github.com/nextstrain/nextclade/blob/f85e2b8c600b289c7be1d22788757a2c070a334a/packages/nextclade/src/analyze/findNucleotideRanges.cpp#L43-L46
Tests are passing unmodified and it no longer crashes on sample data.
Additionally, following the boy-scout rule: "Always leave the campground cleaner than you found it", I removed unnecessary comments and added doc comments.
> fix: off-by-one and illegal array access in findCharacterRanges

- packages/nextclade/src/__tests__/findNucChanges.test.cpp
- packages/nextclade/src/analyze/findNucChanges.cpp
The test `ReportsAlignmentStartAndEnd`
https://github.com/nextstrain/nextclade/blob/b007490e0107a07b65534b175a4ffd6350685963/packages/nextclade/src/__tests__/findNucChanges.test.cpp#L22-L26
was crashing here
https://github.com/nextstrain/nextclade/blob/b007490e0107a07b65534b175a4ffd6350685963/packages/nextclade/src/analyze/findNucChanges.cpp#L40
accesing string `refStripped` at index 3 while it's  length is 3.
This is caused by the fact that the function assumes that query and ref sequences have the same length and cab be indexed in unison, but in the test they were different length.
This should have never happened, as the function is meant to be used on stripped sequences.
We don't want to add any runtime checks for performance reasons, and Nextclade only has access to stripped sequences …
> fix: enforce precondition on stripped sequences, replace invalid test

- packages/common/include/common/safe_string.h
- packages/common/include/common/safe_string_view.h
- packages/common/include/common/safe_vector.h
- packages/nextalign/src/alphabet/aminoacids.cpp
- packages/nextalign/src/alphabet/nucleotides.cpp
- packages/nextalign/src/translate/decode.cpp
- packages/nextalign/src/utils/map.h
- packages/nextclade/src/analyze/findNucChanges.cpp
- packages/nextclade/src/io/CsvWriter.cpp
Since introduction of `safe_vector`, `safe_string` and `save_string_view` classes in  https://github.com/nextstrain/nextclade/pull/671 and https://github.com/nextstrain/nextclade/pull/672, we've observed slowdown on master branch compared to the previous release.
Despite the safe containers being thin wrappers around std containers, they might have introduced an unwanted copy or function call, or perhaps overload resolution does not work the same way and less efficient code is generated.
In any case, these containers are only useful during debugging, so let's conditionally compile them only in debug mode, and alias to std containers in release builds.
> fix: use safe containers only in dev mode

- packages/common/include/common/safe_string.h
- packages/nextalign/src/translate/decode.cpp
I overlooked a couple of places in https://github.com/nextstrain/nextclade/pull/678 and it did not manifest due to conditional compilation. This adds the 2 remaining conversions from safe containers back to std containers. Only relevant in dev mode.
> fix: fix compiler error in dev mode

- packages/nextalign/src/translate/translateGenes.cpp
Followup of https://github.com/nextstrain/nextclade/pull/674
We skip alignment of empty peptides entirely and issue a warning. To be consistent with behavior of nucleotide alignment and to not cause any additional troubles in the alignment code.
> feat: skip alignment of empty peptides

- packages/nextalign/tests/translateGenes.test.cpp
Followup of https://github.com/nextstrain/nextclade/pull/674, https://github.com/nextstrain/nextclade/pull/683
Adds test cases for gene lengths 0, 1, 2 and 3 nucleotides. It's expected that the cases with 0, 1 and 2 nucs will result in an empty peptide and it will not be emitted, and for case of 3 nucs, a 1-AA peptide is emitted.
> test: add tests for trenslateGenes() where peptides are very small

- .all-contributorsrc
- README.md
This adds @dnanto to the list of contributors in the landing page and in the readme
> feat: add contributors

- packages/nextalign_cli/src/cli.cpp
- packages/nextclade_cli/src/commands/executeCommandRun.cpp
It could be that some of the exceptions that occurred in Nextclade and Nextalign libraries were handled, but then the program execution would end with the default implicit 0 exit code returned from main. This was due to a redundant forgotten extra try-catch block.
This removes this try-catch block, so that the exceptions are routed to the correct outer catch clause, which exits with code 1.
Resolves https://github.com/nextstrain/nextclade/issues/679
> fix: exit with correct exit code on exceptions

- packages/common/include/common/debug_trace.h
This was manifesting as a compiler error when debug tracing is enabled. The error is due to missing `fmt::formatter` for `safe_vector`.
Here I convert the formatted for `std::vector` into formatter for `safe_vector` to make sure there is no error anymore.
> fix: ensure custom formatter for safe_vector

- packages/nextalign/CMakeLists.txt
- packages/nextalign/include/nextalign/nextalign.h
- packages/nextalign/src/io/kseqpp.h
- packages/nextalign/src/io/sanitizeSequence.cpp
- packages/nextalign_cli/src/cli.cpp
- packages/nextclade_cli/src/algorithm/runNextclade.cpp
- packages/nextclade_wasm/src/main.cpp
The new fasta parser introduced in https://github.com/nextstrain/nextclade/pull/632 is not sanitizing sequences correctly.
The check is only performed until the first valid character, and the the remainder is copied as-is. This does not match the expectations of nextalign algorithm, which assumes input sequences don't contain any gaps for example. This was leading to incorrect alignment and incorrect insertions being output (consisting entirely from gaps) by nextalign and nextclade cli. Web is not affected because it uses the old, slower parser.
In this PR I remove the sanitization from the parser and add an additional sanitization between the parser and alignment. This should ensure that sequences are still read as fast as possible in the parser thread (there is only one) and that …
> fix: sanitize parsed sequences correctly

- packages/nextclade_cli/src/io/getInputPaths.h
Resolves: https://github.com/nextstrain/nextclade/issues/703
Adds missing CLI args check for a situation where `--input-dataset` is not provided and neither the `--input-virus-properties`.
Now the error message reads as follows:
> [ERROR] Nextclade: Error: Either `--input-dataset` or `--input-virus-properties` is required. Cannot proceed without virus properties. Note: the new required file `virus_properties.json` was introduced in version 1.10.0. You can obtain it from the latest Nextclade dataset. See `nextclade dataset get --help` and https://docs.nextstrain.org/projects/nextclade for more information
> fix: improve error message when virus properties flag is missing

- packages/web/src/components/SequenceView/PeptideMarkerFrameShift.tsx
- packages/web/src/components/SequenceView/PeptideMarkerUnknown.tsx
- packages/web/src/components/SequenceView/SequenceMarkerFrameShift.tsx
- packages/web/src/components/SequenceView/SequenceMarkerGap.tsx
- packages/web/src/components/SequenceView/SequenceMarkerMissing.tsx
- packages/web/src/components/SequenceView/SequenceMarkerMutation.tsx
- packages/web/src/components/SequenceView/SequenceMarkerUnsequenced.tsx
Resolves https://github.com/nextstrain/nextclade/issues/631 https://github.com/nextstrain/nextclade/issues/708 
Followup of https://github.com/nextstrain/nextclade/pull/638 https://github.com/nextstrain/nextclade/pull/644
Continues on the adventure of centering various markers in sequence views, started in https://github.com/nextstrain/nextclade/pull/638 and https://github.com/nextstrain/nextclade/pull/644. 
The goal is to make the different markers to be aligned to their positions in the sequence properly, as well as to be aligned between different other types of markers. The challenge is that there's not enough space to display them and that some of the markers are single positions (substitutions), while others are ranges (Ns), and they can overlap, hide each other, and cause all kinds …
> fix(web): center markers in sequence views

- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/src/tree/TreeNode.cpp
- packages/nextclade/src/tree/findPrivateMutations.cpp
Sorts private substitutions by position in 2 places:
- after merging different types of them right after detection (code is shared for nuc and aa)
- in unison with deletions before attaching to the tree, as opposed to attaching subs first, then dels sequentially (code is different for nuc and aa, because auspice expect aa attachments to be per gene)
This is to improve readability in various lists and in the tree UI.
> feat: sort private mutations

- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/src/qc/ruleSnpClusters.cpp
- packages/nextclade/src/tree/calculateDivergence.cpp
Followup of #710 
We exclude reversions of deletions from mutations considered when calculating divergence. By convention used in the Nextstrain project.
> fix: exclude reversions of dels when calculating divergence

- packages/web/src/components/Results/ListOfInsertions.tsx
This is a leftover from the time when the fragment was displayed as a plain string. 
At some point the fragment has become a component of its own and the "truncated" text was displayed separately, but I forgot to remove the suffix.
This PR fixes it by removing the concatenation of the suffix to the fragment.
> fix: don't add "truncated" suffix to inserted fragment

- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/src/qc/ruleSnpClusters.cpp
- packages/nextclade/src/tree/TreeNode.cpp
- packages/nextclade/src/tree/calculateDivergence.cpp
- packages/nextclade/src/tree/findPrivateMutations.cpp
This excludes reversions of deletions from the array of private substitutions.
After some discussions and trial and error the team decided that they don't belong there.
Previously:
- divergence in Nextstrain traditionally does not account deletions in any form, so we already excluded reversions of deletions in https://github.com/nextstrain/nextclade/pull/722
- we've excluded them earlier in SNP clusters QC rule too https://github.com/nextstrain/nextclade/pull/710
- the only place they show up is the auspice tree
- they are accounted in totalPrivateMutations
In this PR:
The consequences:
- snp clusters stay the same as it is now (after [#710](https://github.com/nextstrain/nextclade/pull/710) / 1.10.2)
- divergence decreases, but same as in …
> fix: exclude reversions of deletions from private substitutions

- packages/nextclade/include/nextclade/nextclade.h
- packages/nextclade/include/nextclade/private/nextclade_private.h
- packages/nextclade/src/io/CsvWriter.cpp
- packages/nextclade/src/io/parseAnalysisResults.cpp
- packages/nextclade/src/io/serializeResults.cpp
- packages/nextclade/src/nextclade.cpp
- packages/nextclade/src/tree/Tree.cpp
- packages/nextclade/src/tree/TreeNode.cpp
- packages/nextclade/src/tree/TreeNode.h
- packages/nextclade_wasm/src/main.cpp
- packages/web/src/algorithms/types.ts
- packages/web/src/components/Results/ColumnCustomNodeAttr.tsx
- packages/web/src/components/Results/ResultsTable.tsx
- packages/web/src/io/serializeResults.ts
- packages/web/src/state/algorithm/algorithm.actions.ts
- packages/web/src/state/algorithm/algorithm.selectors.ts
- packages/web/src/state/algorithm/algorithm.state.ts
- packages/web/src/state/algorithm/algorithmRun.sagas.ts
- packages/web/src/types/auspice/index.d.ts
Extends the Nextclade's Augur tree extension object to provide more data (friendly name of the column and description for the tooltip).
Replaces the `meta.extensions.nextclade.clade_node_attr_keys`array of strings with `meta.extensions.nextclade.clade_node_attrs` array of objects in the auspice tree json.
The expected format is as follows:
```json
{
"meta": {
"extensions": {
"nextclade": {
"clade_node_attrs": [
{
"name": "pango_lineage",
"displayName": "Pango lineage (Nextclade)",
"description": "Pango lineage as inferred by Nextclade from the nearest neighbour in the reference tree. 98% accurate for recent sequences, for higher accuracy use dedicated pangolin software in UShER or pangoLEARN mode"
},
{
"name": "GISAID_clade",
"displayName": "GISAID clade",
"description": "Clades as …
```
> feat: extend tree extensions node clade attrs to be more descriptive

- packages/web/src/components/Common/MutationBadge.tsx
Resolves https://github.com/nextstrain/nextclade/issues/745
There was a redundant null check in the NucleotideMutationBadge component that was causing position of a mutation at first nuc to be ignored (the number 0 is considered nullish in js). This check is redundant anyway, because the position is never null, so I removed it. AminoacidMutationBadge component does not have this check, so it should behave correctly.
> fix(web): ensure correct rendering of mutation at position 0

- scripts/build_locally.sh
By checking for a specific file existence, not directory existence, when deciding on whether to install emsdk
> chore(ci): fix vercel build

- packages/web/src/components/SequenceView/PeptideContext.tsx
Codon 0 (1 in one-based indexing) was not displayed correctly in the peptide context due to `0` treated as `false` in the conditional statement.
> fix(web): display codon 0 correctly in the peptide context

- packages_rs/nextclade-cli/src/cli/nextalign_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade/src/align/params.rs
should be mergable immediately
> fix: typos/wording in cli help texts

- packages_rs/nextclade-cli/examples/simplealign.rs
- packages_rs/nextclade-cli/src/cli/nextalign_cli.rs
- packages_rs/nextclade-cli/src/cli/nextalign_loop.rs
- packages_rs/nextclade-cli/src/cli/nextalign_ordered_writer.rs
- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
- packages_rs/nextclade-cli/src/cli/nextclade_ordered_writer.rs
- packages_rs/nextclade-web/src/wasm/analyze.rs
- packages_rs/nextclade/src/align/align.rs
- packages_rs/nextclade/src/align/gap_open.rs
- packages_rs/nextclade/src/align/score_matrix.rs
- packages_rs/nextclade/src/analyze/aa_changes.rs
- packages_rs/nextclade/src/analyze/find_private_aa_mutations.rs
- packages_rs/nextclade/src/gene/gene_map.rs
- packages_rs/nextclade/src/gene/mod.rs
- packages_rs/nextclade/src/io/errors_csv.rs
- packages_rs/nextclade/src/io/fasta.rs
- packages_rs/nextclade/src/io/gene_map.rs
- packages_rs/nextclade/src/io/gff3.rs
- packages_rs/nextclade/src/io/mod.rs
- packages_rs/nextclade/src/run/nextalign_run_one.rs
- packages_rs/nextclade/src/run/nextclade_run_one.rs
- packages_rs/nextclade/src/translate/translate_genes.rs
- packages_rs/nextclade/src/translate/translate_genes_ref.rs
This modifies behavior of various combinations of `--genemap` and `--genes` flags and makes it consistent in Nextclade CLI and Nextalign CLI.
The new behavior is as follows:
| --genemap  | --genes |                 behavior                   |
|------------|---------|--------------------------------------------|
|     +      |    +    | Take only specified genes                  |
|     +      |         | Take all genes                             |
|            |    +    | Error                                      |
|            |         | Skip translation and codon penalties       |
Notably, if `--genemap` is provided, but `--genes` is not, then all genes will be taken into consideration.
> feat(cli): take all genes if --genes is not provided

- packages_rs/nextclade/src/align/params.rs
- packages_rs/nextclade/src/align/score_matrix.rs
For mutually exclusive options.
The CLI args are:
```
--gap-alignment-side=left
--gap-alignment-side=right
```
Perhaps better to call is "gap placement side" or something like this?
> feat: add gap alignment side enum param

- packages_rs/nextclade-web/src/components/SequenceView/PeptideContext.tsx
This is an extended repeat of https://github.com/nextstrain/nextclade/pull/777, which was accidentally wiped out sometimes during merges.
> fix(web): display codon 0 correctly in peptide context

- packages_rs/nextclade-cli/src/cli/nextalign_cli.rs
- packages_rs/nextclade-cli/src/cli/nextalign_loop.rs
Followup of https://github.com/nextstrain/nextclade/pull/801 where I changed Nextclade CLI args, but forgot to adjust Nextalign CLI args. This PR fixes this omission in Nextalign CLI, by using AlignPairwiseParamsOptional struct, instead of AlignPairwiseParams, and merging incoming CLI params into the defaults, just like it is in Nextclade CLI since #801.
> fix(cli): ensure nextalign cli args for alignment tunning  are optional

- packages_rs/nextclade-web/src/components/Main/DatasetCurrent.tsx
- packages_rs/nextclade-web/src/state/dataset.state.ts
- packages_rs/nextclade-web/src/state/inputs.state.ts
This ensures that sequence view are switched to default gene after navigation to results page. The gene is changed every time the dataset is changed. Otherwise it remembers selected gene (even across runs).
Additionally, it also removes all input files when dataset is changed. Seemingly unrelated, but it was close by in the code and easy to fix.
> fix(web): use default gene in sequence views on startup

- packages_rs/nextclade/src/gene/gene.rs
- packages_rs/nextclade/src/io/gff3.rs
- packages_rs/nextclade/src/translate/translate_genes.rs
- packages_rs/nextclade/src/translate/translate_genes_ref.rs
Followup of https://github.com/nextstrain/nextclade/pull/809
Enum should be less prone to errors, more idiomatic, and perhaps even a tiny bit faster that strings.
Additionally, if strand is missing from GFF file, I set it to `Unknown` (`.`) variant now, instead of to `Forward` (`+`). I think this is more correct. The enum variant `Unknown` can be handled separately if needed, in the code that uses `gene.strand`.
> refactor: replace gene.strand strings with enum variants

- packages_rs/nextclade/src/align/params.rs
Uses [serde's `rename_all` container attribute](https://serde.rs/container-attrs.html#rename_all) to convert variants of `enum GapAlignmentSide` to kebab case during (de)serialization, e.g. in `virus_proprieties.json`.
The enum variants in Rust are by convention in PascalCase, and serde uses them as is. But we want to make the values in `virus_proerties.json` to resemble the values in CLI arguments, and clap seems to be converting enums to kebab case.
If merged, this change requires simultaneous adjustment of datasets using the `gap_alignment_side` param.
> fix: make GapAlignmentSide values in JSON to resemble the ones in CLI

- packages_rs/nextclade-web/src/components/Common/Multitoggle.tsx
- packages_rs/nextclade-web/src/components/Common/NumericInput.ts
- packages_rs/nextclade-web/src/components/Layout/SettingsButton.tsx
- packages_rs/nextclade-web/src/components/SequenceView/SequenceMarkerFrameShift.tsx
- packages_rs/nextclade-web/src/components/SequenceView/SequenceMarkerGap.tsx
- packages_rs/nextclade-web/src/components/SequenceView/SequenceMarkerMissing.tsx
- packages_rs/nextclade-web/src/components/SequenceView/SequenceMarkerMutation.tsx
- packages_rs/nextclade-web/src/components/SequenceView/SequenceMarkerUnsequenced.tsx
- packages_rs/nextclade-web/src/components/Settings/SeqViewSettings.tsx
- packages_rs/nextclade-web/src/components/Settings/SystemSettings.tsx
- packages_rs/nextclade-web/src/state/seqViewSettings.state.ts
This adds toggles to the "Settings" dialog, which allow to toggle markers in sequence views between full-height, half-height at the bottom, half-height at the top and turned off entirely. The toggles are separate for missing, gaps, mutations and unsequenced markers.
The values are remembered in local storage and persist across app launches.
Right now only the nuc view is configurable and only for 4 of hese categories of vertical markers (and not frame shifts for example), but we can add similar toggles to peptide view and other markers later.
Known issues:
> feat(web): configure sequence markers height

- packages_rs/nextclade-web/src/components/Common/NumericField.tsx
- packages_rs/nextclade-web/src/components/SequenceView/SequenceView.tsx
- packages_rs/nextclade-web/src/components/Settings/SeqViewSettings.tsx
- packages_rs/nextclade-web/src/state/seqViewSettings.state.ts
This add a setting that defined maximum number of markers (mutations, deletions, missing, frame shifts) that can be displayed in nucleotide sequence views.
If this number is exceeded, a message is displayed instead.
The value is 300 by default and can be changed in settings. Value is persisted in local storage.
> feat(web): limit number of markers that can be displayed in seq views

- packages_rs/nextclade-web/src/algorithms/types.ts
- packages_rs/nextclade-web/src/state/dataset.state.ts
When `defaultGene` was not set in the dataset, causing "Gene is missing in gene map" text appearing in the sequence view, due to gene view being switched to peptide view for `undefined` gene.
Let's treat the `defaultGene` field as optional and, if it's undefined, default to nuc view.
> fix(web): treat dataset default gene field as optional

- packages_rs/nextclade-web/src/components/Results/ColumnName.tsx
- packages_rs/nextclade-web/src/components/Results/ColumnNameTooltip.tsx
- packages_rs/nextclade-web/src/components/Results/getStatusIconAndText.ts
For sequences that fail alignment the name column was blank and no tooltip was shown. This was due to incorrect conditional logic in the component.
Now the name column and its tooltip are displayed correctly.
> fix(web): ensure seq name column and tooltip are shown for failed seq

- packages_rs/nextclade-web/src/pages/_app.tsx
This ensures that the dataset is properly changed if the launch happens from URL.
With this, the previous dataset, persisted in local storage is used, which causes analysis errors if the requested dataset is not the same as the previously used dataset.
> fix(web): ensure dataset is read from URL

- packages_rs/nextclade-web/src/components/SequenceView/SequenceView.tsx
- packages_rs/nextclade-web/src/state/seqViewSettings.state.ts
This adds some more information to the message appearing instead of sequence view when the limit of markers is exceeded. Now the message shows how many markers it is in total to draw and what is the current limit.
This gives users some more actionable data on how to adjust the limit.
> feat(web): display total number of markers and limit in the message

- packages_rs/nextclade/src/analyze/aa_sub.rs
- packages_rs/nextclade/src/analyze/find_private_aa_mutations.rs
- packages_rs/nextclade/src/tree/tree.rs
- packages_rs/nextclade/src/tree/tree_attach_new_nodes.rs
- packages_rs/nextclade/src/tree/tree_preprocess.rs
This fixes an omission: only nuc mutations were attached to the tree JSON object, and aa mutations were missing.
> fix: ensure aa muts are attached to the tree

- packages_rs/nextclade-web/src/components/SequenceView/ListOfAaChangesFlatTruncated.tsx
- packages_rs/nextclade-web/src/components/SequenceView/SequenceMarkerGap.tsx
This limits number of aminoacid mutation badges in the tooltip of the nucleotide gap marker in sequence view.
This avoid screen overflow when there's too many mutations.
This happens with aa deletions mostly, so ideally we need to group aa deletions into ranges. But it have negative impact to other places which need access to individual deletions and is more work overall. Maybe later.
> feat(web): limit number of aa mut badges in nuc gap tooltips

- packages_rs/nextclade-web/src/components/SequenceView/PeptideMarkerInsertion.tsx
- packages_rs/nextclade-web/src/components/SequenceView/PeptideView.tsx
- packages_rs/nextclade-web/src/components/SequenceView/SequenceMarkerInsertion.tsx
- packages_rs/nextclade-web/src/components/SequenceView/SequenceView.tsx
- packages_rs/nextclade-web/src/theme.ts
This adds display of insertions in nucleotide and aminoacid sequence views
Resolves #769
> feat(web): display nuc and aa insertions in sequence views

- .cargo/config.toml
In order to improve deb experience, this configures build to optimize dependency packages even in dev mode. Nextclade packages themselves stay unoptimized, so that full debug information is available.
Also increases number of codegen units to speedup incremental build process.
> chore(build): speedup debug binaries

- packages_rs/nextclade-web/src/components/Results/ListOfInsertions.tsx
This allows to show up to 20 rows in either nuc or aa insertions tables in the "Ins" column tooltip. Beyond that the list is truncated and the "...truncated" text is shown.
> feat(web): limit tooltips to 20 insertions max

- packages_rs/nextclade-web/src/components/Common/PreviewWarning.tsx
- packages_rs/nextclade-web/src/constants.ts
- packages_rs/nextclade-web/src/pages/_app.tsx
This adds an alert at the top of the page, when:
- the app is build from a git branch that is not `release` branch
- and it's not a dev build (`NODE_ENV != 'development'`)
Alert can be dismissed with a button, but reappears on page refresh (or next visit).
This tries to be minimalistic and to not introduce too many differences between prod and non-prod builds.
> feat: add preview version warning

- Cargo.lock
- packages_rs/nextclade-cli/Cargo.toml
- packages_rs/nextclade-cli/src/cli/nextalign_cli.rs
- packages_rs/nextclade-cli/src/cli/nextalign_loop.rs
- packages_rs/nextclade-cli/src/cli/nextalign_ordered_writer.rs
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
- packages_rs/nextclade-cli/src/cli/nextclade_ordered_writer.rs
- packages_rs/nextclade/Cargo.toml
- packages_rs/nextclade/src/io/fasta.rs
- packages_rs/nextclade/src/io/fs.rs
- packages_rs/nextclade/src/utils/option.rs
Novelties:
- Translations have a dedicated flag, just like any other output. They are not mandatory anymore and are not tied to "all outputs":
```bash
--output-translations='output_dir/gene_{{gene}}.translation.fasta'
```
- "All outputs" flag now means "really all of them". The flag is now named better and not tied to translations:
```
--output-all='my_output_dir/' 
```
- "All outputs" can be filtered by name:
``` 
--output-all='my_output_dir/' --output-selection='fasta,tsv,insertions,translations' 
```
- Nextalign and Nextclade work the same, but Nextclade have more outputs
> CLI redesign for v2

- packages_rs/nextclade-web/src/components/FilePicker/FilePicker.tsx
- packages_rs/nextclade-web/src/components/FilePicker/UploadBox.tsx
- packages_rs/nextclade-web/src/components/FilePicker/UploadBoxCompact.tsx
- packages_rs/nextclade-web/src/components/FilePicker/useUploadZone.ts
- packages_rs/nextclade-web/src/io/AlgorithmInput.ts
Resolves: https://github.com/nextstrain/nextclade/issues/740
Resolves: https://github.com/nextstrain/nextclade/issues/342
This allows upload box to accept multiple input fasta sequences.
If multiple files is dropped or provided using the file dialog, the contents is joined with newlines before passing to the algorithm. The order of files in the resulting joined string cannot be guaranteed, due to unknown order of files, which is browser- and OS-dependent.
> feat(web): upload multiple files

- Cargo.lock
- packages_rs/nextclade/Cargo.toml
- packages_rs/nextclade/src/io/decompression.rs
- packages_rs/nextclade/src/io/fasta.rs
- packages_rs/nextclade/src/io/fs.rs
- packages_rs/nextclade/src/io/mod.rs
This allows to provide compressed fasta files to Nextalign And Nextclade CLI.
If the path in `--input-fasta` contains one of the well-known extensions for compressed files, then it will be decompressed on the fly.
The following compression types are supported:
- gzip (.gz)
- bzip2 (.bz2)
- lzma/lzma2 (.xz)
- zstandard (.zst)
All other files are passed to fasta parser as is.
> feat(cli): support compressed fasta files

- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade/src/io/fs.rs
This allows to strip not only `.fasta`, but also `.fasta.gz` and similar, when deducing file base name which is used for creating output file names.
> fix(cli): correctly find base name in cases like .fasta.gz

- packages_rs/nextclade/src/io/csv.rs
Some of the CLI CSV and TSV files had two header rows due to an extra function call
> fix(cli): prevent writing duplicate csv row

- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade/src/io/decompression.rs
- packages_rs/nextclade/src/io/fs.rs
After transparent compression was introduced, file extension extraction function `extension()` was implemented such that it fails when there is no file extension.
When gradually removing extensions from compressed `files like .fasta.gz` there are 2 calls tomade `extension()`, which correctly detect 2 extensions. However, it was failing on plain `.fasta` files, because after a single extension was removed there wasn't any more.
Here I chose to treat lack of extension as not an error. `extension()` now returns an `Option<String>`, and when there's no extension it returns `None`. The calling code is updated accordingly.
If there's a situation when we need to fail on lack of file extension, then the `Option` can be converted to an error in the calling code or we might introduce another …
> fix(cli): don't treat a lack of extension as error

- packages_rs/nextclade/src/io/fs.rs
- packages_rs/nextclade/src/utils/global_init.rs
This makes the date, severity, file, line parts of the log messages shorter and dimmed, such that the actual messages are more pronounced and the log is less cluttered.
> feat(cli): make CLI log lines more compact

- Cargo.lock
- packages_rs/nextclade-cli/src/cli/common.rs
- packages_rs/nextclade-cli/src/cli/mod.rs
- packages_rs/nextclade-cli/src/cli/nextalign_cli.rs
- packages_rs/nextclade-cli/src/cli/nextalign_loop.rs
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
- packages_rs/nextclade/Cargo.toml
- packages_rs/nextclade/src/io/concat.rs
- packages_rs/nextclade/src/io/csv.rs
- packages_rs/nextclade/src/io/fasta.rs
- packages_rs/nextclade/src/io/file.rs
- packages_rs/nextclade/src/io/fs.rs
- packages_rs/nextclade/src/io/json.rs
- packages_rs/nextclade/src/io/mod.rs
- packages_rs/nextclade/src/io/ndjson.rs
- packages_rs/nextclade/src/io/results_json.rs
One quirk is that now if `--output-basename` is not provided, and input has multiple fasta files it's unclear which one to use for finding basename of output files. I opted for:
- taking the name of the file if only one provided, just like before
- hardcoded string "nextclade"/"nextalign" if there are multiple input files or no files (stdin)
Examples:
```
nextclade run -D dataset/ -O out/ 1.fasta
nextclade run -D dataset/ -O out/ 1.fasta 2.fasta 3.fasta
nextclade run -D dataset/ -O out/ 1.fasta 2.fasta.gz 3.fasta.zst
nextclade run -D dataset/ -O out/ *.fasta
nextclade run -D dataset/ -O out/ *.fasta*
cat 1.fasta 2.fasta | nextclade run -D dataset/ -O out/
xzcat 1.fasta.xz 2.fasta.xz | nextclade run -D dataset/ -O out/
nextclade run -D dataset/ --output-tsv=- 1.fasta | …
```
> feat(cli): make input fasta arg positional, allow multiple files

- packages_rs/nextclade-web/src/components/Common/ButtonTransparent.tsx
- packages_rs/nextclade-web/src/components/FilePicker/FilePicker.tsx
- packages_rs/nextclade-web/src/components/FilePicker/UploadBox.tsx
- packages_rs/nextclade-web/src/components/Main/MainInputFormSequenceFilePicker.tsx
- packages_rs/nextclade-web/src/components/Main/MainInputFormSequencesCurrent.tsx
- packages_rs/nextclade-web/src/hooks/useRunAnalysis.ts
- packages_rs/nextclade-web/src/io/AlgorithmInput.ts
- packages_rs/nextclade-web/src/pages/_app.tsx
- packages_rs/nextclade-web/src/state/inputs.state.ts
- packages_rs/nextclade-web/src/workers/launchAnalysis.ts
This adds a widget which displays a list of currently added fasta files, URLs and pasted snippets and allows to manage them.
Features:
- Add and remove files, URLs or pasted snippets one by one
- One or multiple files can be dropped or selected using file manager
- Example sequences can also be added to the list by clicking to the usual link button
Quirks:
- "Run automatically" if enabled, launches analysis right after the last drop, file selection, url or sequence paste. Multiple files can still be dropped, but only once.
- What's shown on the screenshot below does not fully fit to 1080p screen, so requires scrolling to operate
> feat(web): allow multiple input fasta and control over them

- packages_rs/nextclade-web/src/helpers/formatRange.ts
This avoids a warning when the range is empty as we now consider an empty range  a valid case.
Notably, we've encountered this when a frame shift happens to be due to a 1-base deletion of a stop codon. In this case we still want to report a frame shift situation, even if the frame shift range is technically empty.
> fix(web): make 'invalid range' warning condition more optimistic

- packages_rs/nextclade-web/package.json
- packages_rs/nextclade-web/src/components/Common/BrowserWarning.tsx
- packages_rs/nextclade-web/src/components/Common/PreviewWarning.tsx
- packages_rs/nextclade-web/src/pages/_app.tsx
- packages_rs/nextclade-web/yarn.lock
Related: https://github.com/nextstrain/nextclade/issues/779, https://github.com/nextstrain/nextclade/issues/865
Adds an alert on top of the page if a browser does not meet these criteria:
https://github.com/nextstrain/nextclade/blob/1ec1c2b0726221b301e4d31e8443d792852f312c/packages_rs/nextclade-web/src/components/Common/BrowserWarning.tsx#L13-L17
Firefox and Chrome versions are chosen semi-randomly among versions released circa 2017 (5 years ago), which should give some room. Chrome here includes all the Chromium-based derivatives which don't modify User-Agent string too much (including Brave for example).
Just to be sure, I added Edge 79 as the first Chromium-based version.
Safari support is dropped entirely due to lack of support of nested webworkers: …
> feat(web): add warning for unsupported browsers

- packages_rs/nextclade-web/src/pages/_app.tsx
Nextclade Web has been hiding some of the errors that occur during initialization. Notably, if dataset server is not reachable or dataset index fetch fails for any reason, then Nextclade would just show loading spinner indefinitely.
This PR ensures that the error is properly handled and that an error message is shown in these cases.
> fix(web): ensure init errors are not hidden

- .circleci/config.yml
- docker-cross
- docker-dev
- docker/docker-dev.dockerfile
> chore(ci): ensure better compatibility of linux gnu binaries

- docker-dev
Followup of #873
Let's downgrade base image for CI builds to Debian 8, for even better compatibility
> chore(ci): ensure even better compatibility of linux gnu binaries

- packages_rs/nextclade-web/src/filtering/filterByAminoacidChanges.ts
This was sometimes causing a crash of the web app when filtering by aminoacids. The filed `queryAa` was not spelled correctly and the lodash `intersectionWith()` function's typings did not catch the type mismatch.
> fix(web): rectify incorrect field name

- packages_rs/nextclade-cli/src/cli/nextalign_loop.rs
- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
Nextclade v2 crashes when encounters unknown nucleotide letters when converting fasta string to the internal sequence representation.
This PR aligns behavior with v1: sequences with unknown nucleotide letters are now ignored, excluded from results, added to errors.csv, the warning message is printed and the run continues.
> fix(cli): don't crash on unknown nucleotide characters

- packages_rs/nextclade/src/tree/tree_attach_new_nodes.rs
This adds qc status to the tree json, previously missing.
This should ensure that they QC status is shown on the tree viz as it was in Nextclade v1.
> fix: add missing qc status to tree json

- packages_rs/nextclade/src/io/compression.rs
- packages_rs/nextclade/src/io/csv.rs
- packages_rs/nextclade/src/io/errors_csv.rs
- packages_rs/nextclade/src/io/fasta.rs
- packages_rs/nextclade/src/io/file.rs
- packages_rs/nextclade/src/io/insertions_csv.rs
- packages_rs/nextclade/src/io/mod.rs
- packages_rs/nextclade/src/io/ndjson.rs
- packages_rs/nextclade/src/io/nextclade_csv.rs
Adds compression support for output files: if output filename contains one of the supported extensions, the outputs will be transparently compressed. Example `--output-fasta=aligned.fasta.xz`. Supported formats as the same as for input decompression: gz, bz2, xz, zstd. Default compression levels are used.
To make it compile, I had to additionally:
- change some of the lifetime parameters in CSV and NDJSON writer, because they were unnecessarily limiting
- remove a very tricky `into_inner()` methods in CSV and NDJSON writer, which required `Sync`trait on inner writer, while zstd writer did not support that. For that, in a few places, instead of getting inner writer and getting a string out of it, I managed to just use vec as an inner writer in these places. So `into_inner()` method was no …
> feat(cli): add output file compression

- Cargo.lock
- packages_rs/nextclade-cli/Cargo.toml
- packages_rs/nextclade-cli/src/cli/mod.rs
- packages_rs/nextclade-cli/src/cli/nextalign_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-cli/src/cli/verbosity.rs
Currently --verbosity, --silent, -v and -q args are missorted in the --help message text.
Here I inline the `clap-verbosity-flag` crate (only 1 file) and modify it, adding our custom flags and `display_order` annotations, such that the args are shown in the very end of the message, just before the `--help` arg.
> feat(cli): organize verbosity flags towards the end of help message

- packages_rs/nextclade/src/align/params.rs
- packages_rs/nextclade/src/align/seed_alignment.rs
> fix: avoid large allocations during alignment

- packages_rs/nextclade/src/align/insertions_strip.rs
- packages_rs/nextclade/src/analyze/aa_changes.rs
- packages_rs/nextclade/src/analyze/nuc_changes.rs
This adds sorting of nuc and aa mutations, deletions and insertions right after they are extracted. This should ensure that they are sorted in the the output files, which improves readability.
> feat: sort mutations, deletions and insertions

- .cargo/config.toml
This enables optimizations even in dev and test mode, to some of the third-party packages that are known to be slow. This should hopefully make dev experience a bit better.
> chore: speedup dev and test binaries

- packages_rs/nextclade-cli/src/cli/nextalign_loop.rs
- packages_rs/nextclade-cli/src/cli/nextalign_ordered_writer.rs
- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
- packages_rs/nextclade-cli/src/cli/nextclade_ordered_writer.rs
- packages_rs/nextclade-web/src/wasm/analyze.rs
- packages_rs/nextclade-web/src/workers/nextcladeWasm.worker.ts
- packages_rs/nextclade/src/align/align.rs
- packages_rs/nextclade/src/align/backtrace.rs
- packages_rs/nextclade/src/align/params.rs
- packages_rs/nextclade/src/constants.rs
- packages_rs/nextclade/src/io/nextclade_csv.rs
- packages_rs/nextclade/src/lib.rs
- packages_rs/nextclade/src/run/nextalign_run_one.rs
- packages_rs/nextclade/src/run/nextclade_run_one.rs
- packages_rs/nextclade/src/translate/translate_genes.rs
- packages_rs/nextclade/src/types/outputs.rs
Adds flag `--retry-reverse-complement` which enables additional attempt of seed matching when initial attempt fails. The second attempt is performed on reverse-complemented sequence.
If the flag is provided, as a consequence:
- the output alignment, peptides and analysis results correspond to this modified sequence and not to the original
- sequence name gets a suffix appended to it for all output files (fasta, `seqName` column, node name on the tree etc.)
- in output files, there is a new field/column: `isReverseComplement`, which contains "true" if the corresponding sequence underwent reverse-complement transformation
This functionality is opt-in and the default behavior is unchanged: skip sequence and emit a warning.
> feat: retry with reverse complement when seed matching fails

- packages_rs/nextclade-cli/src/bin/nextalign.rs
- packages_rs/nextclade-cli/src/bin/nextclade.rs
- packages_rs/nextclade-cli/src/cli/nextalign_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
Resolves https://github.com/nextstrain/nextclade/issues/899
This consolidates subcommand handling on one place and prevents inconsistencies when certain subommands need to be handled in 2 places but it's not done, causing a crash.
> fix(cli): avoid errors when certain subcommands are invoked

- CHANGELOG.md
- packages_rs/nextclade-cli/src/dataset/dataset_download.rs
Resolves #908 
Positional args in Rust tripped us up here, maybe there's a less bug-prone way to do this.
I'm still wondering though: why is there no error when the default dataset is passed? Surely there must still be a file parsing problem. Do we quietly not overwrite then? That's not great. We should still throw an error if someone wants to overwrite but the file they're overwriting with is bad.
> fix: mixed up input-prc and input-virus-properties

- CHANGELOG.md
- packages_rs/nextclade-cli/src/cli/nextalign_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade/src/io/fs.rs
Resolves: https://github.com/nextstrain/nextclade/issues/907
This rolls an in-house version of `add_extension()` function which always adds an extension to a `PathBuf`.  This is different from `PathBuf::with_extension()` which may replace or add extension depending on what the path is.
This solves a problem with basenames containing dots, as described in the issue: `PathBuf::with_extension()` thought that they are extensions and replaced the last one. But we always want to add, not replace.
> fix(cli): prevent truncation of  components if basename contains dots

- packages_rs/nextclade-cli/src/cli/nextalign_ordered_writer.rs
- packages_rs/nextclade-cli/src/cli/nextclade_ordered_writer.rs
- packages_rs/nextclade/src/align/align.rs
- packages_rs/nextclade/src/io/fasta.rs
- packages_rs/nextclade/src/run/nextclade_run_one.rs
Followup of https://github.com/nextstrain/nextclade/pull/887
We reconsidered: we will only append suffix to sequence names in aligned fasta output. So this removes the suffix from all other places (incl. translation fastas).
> feat: remove reverse complement suffix from outputs except nuc fasta

- Cargo.lock
- packages_rs/nextclade-cli/Cargo.toml
- packages_rs/nextclade-web/Cargo.toml
- packages_rs/nextclade/Cargo.toml
These updates break dev mode in web app. WASM calls crash on Chromium with
```
TypeError: Cannot read properties of undefined (reading 'buffer')
at eval (src/gen/nextclade-wasm_bg.js:1357:97)
```
and on Firefox with
```
_nextclade_wasm_bg_wasm__WEBPACK_IMPORTED_MODULE_0__.memory is undefined
```
These updates were purely nice to haves, so let's revert them, to unblock the development process. We will upgrade and resolve these issues when we have some spare time.
I did not revert Rust version upgrade, keeping it 1.62.0, because it does not seem to affect things.
> Revert recent dependency updates

- docs/user/output-files.md
- packages_rs/nextclade-cli/src/cli/nextalign_ordered_writer.rs
- packages_rs/nextclade-cli/src/cli/nextclade_ordered_writer.rs
- packages_rs/nextclade-web/src/algorithms/types.ts
- packages_rs/nextclade-web/src/hooks/useExportResults.ts
- packages_rs/nextclade-web/src/wasm/main.rs
- packages_rs/nextclade-web/src/workers/ExportThread.ts
- packages_rs/nextclade-web/src/workers/nextcladeWasm.worker.ts
- packages_rs/nextclade/src/io/insertions_csv.rs
- packages_rs/nextclade/src/io/ndjson.rs
- packages_rs/nextclade/src/io/nextclade_csv.rs
- packages_rs/nextclade/src/io/results_json.rs
- packages_rs/nextclade/src/types/outputs.rs
Resolves: https://github.com/nextstrain/nextclade/issues/921
It was reported by @tseemann that in Nextclade v2 CSV and TSV rows are not written for failed sequences. While in v1 they were. This was unintended.
In this PR:
- CSV, TSV, NDJSON rows for failed entries are now also written (only `errors` column is populated)
- JSON output now has a separate `errors` filed at the root of the object, with all failed entries
- NDJSON rows are also written for failed entries. They only contain `index`, `seqName` and `errors` fields.
- new columns are written into CSV and TSV outputs: `warnings` and `failedGenes`, which include any warnings emitted for a sequence as well as a list of genes that failed translation. Now all columns of the "errors.csv" file are also in the CSV and TSV results files.
> fix: write failed sequence results (errors) to into outputs

- packages_rs/nextclade-web/src/components/Common/BrowserWarning.tsx
Resolves https://github.com/nextstrain/nextclade/issues/896
This makes the warning to appear in a modal, so that it's harder to miss. Also adds links to official websites of Chrome and Firefox.
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/9403403/177699693-fe9e0606-55bc-4b39-a9d2-e519afc3980b.png">
</img>
</a>
> feat(web): improve unsupported browser warning

- docs/conf.py
- docs/environment.yml
The new extension has sphinx_copybutton pre-installed and configured. This change enables it here.
This also makes it easier to configure other extensions across multiple docs projects.
https://github.com/nextstrain/sphinx-theme/issues/30
> docs: Install nextstrain.sphinx.theme extension

- packages_rs/nextclade/src/analyze/aa_changes.rs
When the first gene is very close to the start of the sequence, as in flu_yam_ha, and a mutation happens in the first codon, and underflow would happen inside a clamp.
So while nothing would go wrong logic wise, Rust was oversensitive here, panicking.
It would still be good to check that context behaves as expected in this edge case - as this seems to not occur commonly - outside of yam.
This PR needs to be merged in order for yam dataset to work again - bit tricky - we should exclude the range 2.0.0 to 2.3.0 for flu_yam_ha, what should we set as min version? Maybe 2.3.1 therefore not giving a new dataset to v1 users? I think that's OK as yam hardly changes.
> fix: underflow when mutation in gene close to start

- packages_rs/nextclade-cli/src/cli/nextalign_loop.rs
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_dataset_get.rs
- packages_rs/nextclade-cli/src/cli/nextclade_dataset_list.rs
- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
- packages_rs/nextclade-cli/src/dataset/dataset_download.rs
- packages_rs/nextclade-cli/src/io/http_client.rs
- packages_rs/nextclade/src/io/gene_map.rs
This adds `--dataset-name` (`-d`) to `run` command, which allows to download a dataset with default parameters and run with it immediately, in one command.
For example this command.
```bash
nextclade run --output-all=out --dataset-name=sars-cov-2 sequences.fasta
```
will download the latest default sars-cov-2 dataset into memory and will run analysis with these dataset files.
This is a convenience shortcut for the usual combination of `dataset get` + `run`. The dataset is not persisted on disk and downloaded on every run.
This also adds `--server` flag to the `run` command, which works exactly the same as in the `dataset get` and `dataset list` commands.
> feat: add "download dataset and run" shortcut"

- packages_rs/nextclade-web/src/components/Results/ColumnName.tsx
- packages_rs/nextclade-web/src/components/Results/ColumnNameTooltip.tsx
- packages_rs/nextclade-web/src/state/results.state.ts
Followup of https://github.com/nextstrain/nextclade/pull/946
This adds little yellow icons in the "Sequence name" column when a sequence has the same name as other sequences in the same run. Indices of these sequences are additionally listed in the tooltip.
> feat(web): report duplicate sequence names

- packages_rs/nextclade-web/src/state/results.state.ts
Currently duplicate sequence name data persists across unrelated runs of Nextclade Web. This causes incorrect reporting of duplicates.
This PR ensures that duplicate sequence name data does not persist across runs.
> fix: correctly reset duplicate sequence name map on new runs

- packages_rs/nextclade-web/src/components/Main/Downloads.tsx
The currently deployed version links to non-existent v1 files. 
I decided to remove direct links, because we have many more platforms now, and only leave the link to GitHub Releases.
I also thought that removing extra explanations (found in the docs) and making buttons more prominent will make it easier for users to discover these links.
> feat(web): correct and restyle download links on main page

- packages_rs/nextclade-web/src/filtering/filterByAminoacidChanges.ts
- packages_rs/nextclade-web/src/filtering/filterByNucleotideMutations.ts
Related to: https://github.com/nextstrain/nextclade/issues/961
This removes casts in amino acid and nucleotide filtering code which have a potential to cause crashes in certain cases. I made `undefined`-comparison more lax, such that now it also checks for `null` and added default values to anything that can be nil.
Even though I cannot reproduce the issue, this hopefully should fix it.
> fix: make filtering code safer

- packages_rs/nextclade-web/src/components/Main/ButtonCustomize.tsx
- packages_rs/nextclade-web/src/io/fetchDatasets.ts
- packages_rs/nextclade-web/src/state/inputs.state.ts
Resolves: https://github.com/nextstrain/nextclade/issues/998
Now when `dataset-name` is present in the URL params, Nextclade will try to find and set this dataset as current, regardless of whether the `input-fasta` is also provided. This allows to set a dataset and customize its files using URL params, with intent to then load fasta manually.
Normally, when navigation happened from such URL, there is no obvious sign that dataset files were changed. I added a little indicator with a counter to make it more obvious when dataset files are customized.
Example: 
https://nextclade-git-feat-web-url-read-dataset-witho-0511cb-nextstrain.vercel.app/?dataset-name=sars-cov-2-21L&input-tree=https%3A%2F%2Fapi.codetabs.com%2Fv1%2Fproxy%3Fquest%3Dhttps%3A%2F%2Fnextstrain.org%2Fcharon%2FgetDataset%3Fprefix …
> fix(web): read dataset name from URL, even when fasta is not provided

- packages_rs/nextclade-web/src/components/Main/DatasetCurrent.tsx
- packages_rs/nextclade-web/src/components/Main/DatasetSelector.tsx
Currently release users see master dataset changelog. Here I change the link such that they see dataset changelog on release branch, i.e. only released dataset changes.
> fix: link to release dataset changelog

- packages_rs/nextclade-web/src/components/Common/FormattedText.tsx
- packages_rs/nextclade-web/src/components/Results/ResultsTable.tsx
Format text of custom phenotype columns. This text comes from a JSON string, so formatting capabilities are very limited. Here I split the incoming string on `\n` and create paragraphs (`<p>`)  from each fragment.
> feat(web): format tooltip text

- packages_rs/nextclade/src/run/nextclade_run_one.rs
- packages_rs/nextclade/src/types/outputs.rs
Removes `results[].phenotypeValues.nameFriendly` and `results[].phenotypeValues.description` from output JSON and NDJSON. These fields were not intended to be used, are repeated and increase file size needlessly.
> fix: remove unused data from outputs

- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
- packages_rs/nextclade-cli/src/cli/nextclade_ordered_writer.rs
- packages_rs/nextclade-web/src/hooks/useExportResults.ts
- packages_rs/nextclade-web/src/wasm/main.rs
- packages_rs/nextclade-web/src/workers/ExportThread.ts
- packages_rs/nextclade-web/src/workers/nextcladeWasm.worker.ts
- packages_rs/nextclade/src/io/results_json.rs
Adds descriptions of phenotype attributes to `.phenotypeAttrKeys` of JSON output. This is for symmetry with the similarly implemented `.cladeNodeAttrKeys` attributes.
> fix: add descriptions for phenotype attributes to outputs

- packages_rs/nextclade-web/src/state/results.state.ts
- packages_rs/nextclade-web/src/types/auspice/index.d.ts
- packages_rs/nextclade/src/tree/tree.rs
Related: https://github.com/nextstrain/nextclade_data/issues/39
Allows hiding custom clade columns from Nextclade Web.
In order to hide a column from Nextclade Web, set `"hideInWeb": true` in `meta.extensions.nextclade.clade_node_attrs` in reference tree JSON, for example:
```json
"extensions": {
"nextclade": {
"clade_node_attrs": [
{
"name": "WHO_name",
"displayName": "...",
"description": "...",
"hideInWeb": true
}
]
}
}
```
The columns/fields will still be rendered in all other outputs: TSV, CSV, JSON and NDJSON
> feat: allow hiding custom clade columns

- packages_rs/nextclade-web/src/components/Results/ResultsTable.tsx
- packages_rs/nextclade-web/src/components/Results/ResultsTableRow.tsx
- packages_rs/nextclade-web/src/components/Results/ResultsTableRowResult.tsx
- packages_rs/nextclade-web/src/state/results.state.ts
Followup of https://github.com/nextstrain/nextclade/pull/1006
The PR https://github.com/nextstrain/nextclade/pull/1006 introduced a bug: it filters away hidden columns from recoil state, thus making them unavailable for export functions. The mismatch in expected columns caused crash on Rust side.
Here I modify the filtering logic, moving it to the actual rendering site, instead of filtering globally. This way, hidden columns are not rendered, but are still be available for export.
> fix(web): crash when exporting files in web

- docs/user/nextclade-web.md
- packages_rs/nextclade-web/infra/lambda-at-edge/modifyOutgoingHeadersForApi.lambda.js
- packages_rs/nextclade-web/src/io/fetchDatasets.ts
- packages_rs/nextclade-web/src/io/fetchDatasetsIndex.ts
- packages_rs/nextclade-web/src/pages/_app.tsx
- packages_rs/nextclade-web/src/state/dataset.state.ts
- packages_rs/nextclade-web/tools/server/dataServer.ts
Allows to dynamically set dataset server root URL in Nextclade Web on runtime.
It is sufficient to add URL parameter `dataset-server` with the value containing URL to the root of the dataset file server (containing `index_v2.json`), and Nextclade Web will fetch dataset index and all dataset files from this server instead of the default:
```url
?dataset-server=http://example.com
```
The localhost URLs should also work:
```url
?dataset-server=http://localhost:27722
```
This is equivalent to `--server` flag in Nextclade CLI. 
This should facilitate testing of custom datasets in Nextclade Web.
> feat(web): dynamically set dataset server root using a URL param

- packages_rs/nextclade-web/src/helpers/getNumThreads.ts
Despite "thread" (actually webworker) initialization is supposed to be concurrent, there seem to be a clear trend of increased initialization time as number of threads increased. This is likely due to data transfer overhead between workers.
Here I reduce number of threads that can be initialized with default settings.
But these settings can always be altered in the "Settings" dialog.
> feat(web): reduce default number of threads to speedup initialization

- Cargo.lock
- docker-dev
- packages_rs/nextclade/Cargo.toml
- packages_rs/nextclade/src/io/json.rs
Resolves https://github.com/nextstrain/nextclade/issues/1018
When tree JSON is sufficiently nested, `serde_json` fails to parse it into the `AuspiceTree` `struct`  with:
```
recursion limit exceeded at line <line> column <column>
```
This problem has been reported before in `serde_json` in https://github.com/serde-rs/json/issues/334, and the solution allowing to remove the recursion limit was implemented in the form of [`Deserializer::disable_recursion_limit`](https://docs.rs/serde_json/latest/serde_json/struct.Deserializer.html#method.disable_recursion_limit) traded off to the increased risk of overflowing the call stack.
So here I implemented the suggested solution, by calling the `disable_recursion_limit()` on deserializer. I am also mitigating the risk of stack overflow by using …
> fix: ensure parsing of large, highly-nested tree JSONs

- Cargo.lock
- packages_rs/nextclade-cli/Cargo.toml
- packages_rs/nextclade-cli/src/bin/nextalign.rs
- packages_rs/nextclade-cli/src/bin/nextclade.rs
- packages_rs/nextclade/Cargo.toml
Resolves: https://github.com/nextstrain/nextclade/issues/1027
Here I remove Mimalloc, because  was not configured correctly, due to a mistake in `cfg` conditional, and even when set up correctly does not make Nextclade any faster (see the linked issue for benchmarks).
> perf: use default memory allocator

- packages_rs/nextclade/src/io/csv.rs
- packages_rs/nextclade/src/io/fasta.rs
- packages_rs/nextclade/src/io/file.rs
- packages_rs/nextclade/src/io/fs.rs
- packages_rs/nextclade/src/io/json.rs
- packages_rs/nextclade/src/io/ndjson.rs
Here I refactor file I/O code in Nextclade CLI.
I am introducing and then reusing the function `open_file_or_stdin()` in all places where a file needs to be read (except for when reading a zip archive, where it needs a seekable stream, so stdin won't work), and the function `create_file_or_stdout()` for all places where a  file needs to be written.
This reduces code duplication (of compression and buffering code specifically) and also introduces consistent buffering and compression support to all the input and output files (except the zip mentioned above).
> feat(cli): improve file io logic

- packages_rs/nextclade-web/src/i18n/i18n.auspice.ts
Here I import and add "it", "ja" and "tr" locales, which are available in Auspice, but have not been used so far.
> feat(web): enable more locales in auspice

- packages_rs/nextclade-web/src/i18n/i18n.auspice.ts
- packages_rs/nextclade-web/src/i18n/i18n.ts
Here I enable immediate mode of i18next initialization, by setting `initImmediate: true` option, forcing synchronous initialization (without `Promises`).
This allows us to use `i18n` object and `t()` function globally, for example outside of React components.
Previously there was as risk of using them before initialization completes (depending on whether initialization promise resolves by then or not). But now it is guaranteed to be correct.
See: https://www.i18next.com/overview/configuration-options#text-initimmediate
> fix(web): ensure timely i18n initialization

- packages_rs/nextclade-web/.eslintrc.js
- packages_rs/nextclade-web/src/components/Main/CladeSchema.tsx
- packages_rs/nextclade-web/src/constants.ts
- packages_rs/nextclade-web/src/i18n/resources/ar/common.json
- packages_rs/nextclade-web/src/i18n/resources/de/common.json
- packages_rs/nextclade-web/src/i18n/resources/el/common.json
- packages_rs/nextclade-web/src/i18n/resources/en/common.json
- packages_rs/nextclade-web/src/i18n/resources/es/common.json
- packages_rs/nextclade-web/src/i18n/resources/fa/common.json
- packages_rs/nextclade-web/src/i18n/resources/fr/common.json
- packages_rs/nextclade-web/src/i18n/resources/he/common.json
- packages_rs/nextclade-web/src/i18n/resources/hi/common.json
- packages_rs/nextclade-web/src/i18n/resources/id/common.json
- packages_rs/nextclade-web/src/i18n/resources/it/common.json
- packages_rs/nextclade-web/src/i18n/resources/ja/common.json
- packages_rs/nextclade-web/src/i18n/resources/ko/common.json
- packages_rs/nextclade-web/src/i18n/resources/nl/common.json
- packages_rs/nextclade-web/src/i18n/resources/pt/common.json
- packages_rs/nextclade-web/src/i18n/resources/ru/common.json
- packages_rs/nextclade-web/src/i18n/resources/ta/common.json
- packages_rs/nextclade-web/src/i18n/resources/th/common.json
- packages_rs/nextclade-web/src/i18n/resources/tr/common.json
- packages_rs/nextclade-web/src/i18n/resources/ur/common.json
- packages_rs/nextclade-web/src/i18n/resources/vi/common.json
- packages_rs/nextclade-web/src/i18n/resources/zh/common.json
This replaces inline svg file with a URL to the svg file in the   https://github.com/nextstrain/ncov-clades-schema/ repo.
This way we don't need to do a file copy on every update.
> feat: hotlink clade schema

- docker-cross
- docker-dev
- docker/docker-dev.dockerfile
- scripts/test-linux-distros
We use good old Debian 7 (codename: wheezy, glibc 2.14) as a base docker image for our Linux builds, to ensure the best compatibility of Nextclade CLI binaries across Linux distributions.
However, builds on have failed recently. The gpg keys from package repositories of  Debian 7 have expired and don't seem to be renewing for a while. This can be overridden and makes package installation potentially insecure.
In order to resolve that, here I migrate builds to `quay.io/pypa/manylinux2014_x86_64` image (glibc 2.17). This is CentOS 7-based image which is used by Python community to build packages which work on many different Linux distros.
Downside: we lose compatibility with Linux distros with glibc < 2.17, such as debian 7.
Upside: minimum of glibc 2.17 means that we can now use more …
> chore: migrate linux ci build to centos

- rust-toolchain.toml
We can now afford it due to https://github.com/nextstrain/nextclade/pull/1057
> chore" upgrade rust to 1.65

- .github/workflows/bioconda.yml
- scripts/publish_bioconda
- scripts/update-bioconda.py
Adds a script and a GHA workflow to publish new version on bioconda. 
The workflow is normally to be triggered by a GitHub release (but can also be triggered manually or through API). It downloads the binaries, gets their version,  commits and pushes updated `meta.yaml` to https://github.com/nextstrain/bioconda-recipes and then creates a PR from there to https://github.com/bioconda/bioconda-recipes/branches.
> chore(ci): publish to bioconda

- packages_rs/nextclade-web/src/components/Main/DatasetCurrent.tsx
- packages_rs/nextclade-web/src/components/Main/DatasetSelector.tsx
- packages_rs/nextclade-web/src/components/Main/DatasetSelectorList.tsx
- packages_rs/nextclade-web/src/hooks/useRunAnalysis.ts
- packages_rs/nextclade-web/src/io/fetchDatasets.ts
- packages_rs/nextclade-web/src/io/fetchDatasetsIndex.ts
- packages_rs/nextclade-web/src/io/fetchSingleDatasetFromUrl.ts
- packages_rs/nextclade-web/src/pages/_app.tsx
- packages_rs/nextclade-web/src/state/dataset.state.ts
- packages_rs/nextclade-web/src/state/results.state.ts
- packages_rs/nextclade-web/src/types.ts
- packages_rs/nextclade-web/src/workers/launchAnalysis.ts
This fixes a problem where datasets could not be selected in dataset selector of Nextclade Web if they have the same name.
In this PR the datasets are now distinguished by the unique combination of attributes, not only name, and when rendering also by the `.id` field, which was added in data repo here: https://github.com/nextstrain/nextclade_data/pull/52
> fix: identify datasets uniquely

- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_dataset_list.rs
This introduces special value "all" for `--reference` param of `dataset list` command. And it is now set as default value for this flag. When it's in force, datasets with all reference sequences are included into the displayed list.
Additionally sorting is applied to group datasets with related attributes visually.
> fix(cli): show non-default references in "dataset list" command

- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
Followup to https://github.com/nextstrain/nextclade/pull/1063
Fix the meaning and formatting of the help text for the modified `--reference` arg.
> fix(cli): correct help text

- packages_rs/nextclade/src/qc/qc_config.rs
This fixes the bug when the QC score is 0 when the following QC fields are missing from `qc.json`:
```
.privateMutations.weightLabeledSubstitutions
.privateMutations.weightReversionSubstitutions
.privateMutations.weightUnlabeledSubstitutions
```
In this case Nextclade assumed value 0, and ending up with calculating QC score of 0. Not all datasets were adjusted, so some datasets don't have these fields.
Here I set the default of these weights to 1.0 if they are missing, such that QC have some sensible values again.
> fix: set default weights in private mutations qc check to 1

- scripts/publish_bioconda
In hope to remove the need for `read:org` permission on the GH token.
> chore(ci): remove 'gh auth status' call

- scripts/update-bioconda.py
This is a requirement of bioconda it seems. Otherwise the "lint" check does not pass.
> chore(ci): reset bioconda build number on version bump [skip ci]

- packages_rs/nextclade-web/src/helpers/takeFirstMaybe.ts
- packages_rs/nextclade-web/src/io/createInputFromUrlParamMaybe.ts
- packages_rs/nextclade-web/src/pages/_app.tsx
Add special handling of value `example` to `input-fasta` URL param in Nextclade Web.
When `input-fasta=example` param is added, Nextclade Web will automatically start the analysis of example sequences (just like when clicking "Load example" on main page). The dataset should be provided with
This is handy when testing and debugging things.
Can also be used to combine external fasta and the examples. In this case, add multiple `input-fasta` parameters, e.g.
```
?input-fasta=example&input-fasta=http://example.com/my.fasta&dataset-name=my-dataset-name
```
> Allow to add example sequences using URL param

- CHANGELOG.md
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
Followup of https://github.com/nextstrain/nextclade/pull/1081
Turns out setting `group` for related arguments in `clap` makes them exclusive, so for example `--output-all` and `--output-tsv` could not be used together after the [changes](https://github.com/nextstrain/nextclade/pull/1081/files#diff-b5e102bcc2cc46bbfcf5a19927b6adad0a8a0adb4c0f80b7a46bcf05fdafbd28L385-R500) in https://github.com/nextstrain/nextclade/pull/1081.
In order to fix that I remove the `group` and check the presence of one of `--output-all`, `--output-csv`, `--output-tsv` manually. This is the constraint required for `--output-columns-selection`. I tried to express with the `group`, but that did had the aforementioned unwanted side effect, breaking bioconda tests: …
> fix: ensure `--output-all`, `--output-tsv`, `--output-csv` can be used together again

- packages_rs/nextclade-web/src/state/settings.state.ts
Resolves https://github.com/nextstrain/nextclade/issues/1084
The gene map (genome annotation) schema is not aligned with sequence views (it is narrower).
This was caused by extra width added to the gene map name column to the left of the schema. There are clade-like columns in the inputs that are hidden from web app. However, they were still counted when calculating gene map width.
Here I filter out the hidden clade-like entries before calculating width. This should resolve the issue.
> fix(web): ensure correct width of gene map

- packages_rs/nextclade-web/src/components/Results/HelpTips/HelpTipsColumnRowIndex.mdx
- packages_rs/nextclade-web/src/components/Results/ResultsTable.tsx
- packages_rs/nextclade-web/src/components/Results/ResultsTableRow.tsx
- packages_rs/nextclade-web/src/components/Results/ResultsTableRowResult.tsx
- packages_rs/nextclade-web/src/components/Results/ResultsTableStyle.tsx
Resolves https://github.com/nextstrain/nextclade/issues/1085
Adds column with index of the row in the table. Useful for visual search and counting of sorted and filtered results.
Not to be confused with sequence index.
Row indices always start with 0 and sorted in ascending order, and do not change their position when sorting or filtering the results.
Indices are 0-based.
These indices are not a part of output files. Spreadsheet software like Excel usually already have rows numbered in this manner.
In this screenshot, the "Row index" column is denoted as "#". The cells in this column have the same background as table header row, to indicate special meaning, just like in Excel. I sorted rows by clade and selected rows with 22F. If you look at row indices, you can quickly see that there are …
> feat(web): add row index column to results table

- packages_rs/nextclade-web/src/components/Layout/LayoutResults.tsx
- packages_rs/nextclade-web/src/components/Results/ResultsPage.tsx
On smaller screens the "Download", "Tree" and other buttons are overflowing, so that they are not visible by default and horizontal scrolling is required to see them.
Here I change the layout such that the panel with buttons does not overflow along with table and so the buttons are always visible. Table is still scrollable.
> feat(web): always show action buttons on results page

- packages_rs/nextclade/src/align/align.rs
- packages_rs/nextclade/src/align/seed_alignment.rs
Resolves https://github.com/nextstrain/nextclade/issues/554
As concluded in the issue, here I just append another sentence to the text of alignment errors, to add some more context and actionable information to the user:
```
This is likely due to a low quality of the provided sequence, or due to using incorrect reference sequence.
```
As before, these messages will appear as errors for nuc alignment and as per-gene warnings for aa alignment.
Additionally I modified the message for "no seed matches" error. It is triggering when there is less than 2 seed matches, so  "no seed matches: 1 seed match" seemed a bit confusing. Now it says "not enough seed matches".
> feat: improve alignment errors

- packages_rs/nextclade-cli/src/cli/nextclade_ordered_writer.rs
- packages_rs/nextclade/src/io/nextclade_csv.rs
Resolves https://github.com/nextstrain/nextclade/issues/1101
Nextclade emits the new `index` column in case of sucessful analysis, but is missing it when outputs an error row  into CSV and TSV. That's a big whoopsie-doopsie which caused havoc in downstream applications.
Here I fix the omission by writing the `index` column in case of errors too.
> fix(cli): emit index csv/tsv column when there's an error

- docker-dev
Resolves https://github.com/nextstrain/nextclade/issues/1107
(or rather attempts to)
We are using `docker buildx` command, which AFAIU implies `DOCKER_BUILDKIT=1`.  
But someone on the internet* suggested that removing it or setting `DOCKER_BUILDKIT=0` may resolve the errors we are having. I'd like to keep using buildkit though, so don't know if any of it is a good idea. But let's give it a try on a branch.
\* - https://github.com/docker/buildx/issues/415, https://stackoverflow.com/questions/64221861/an-error-failed-to-solve-with-frontend-dockerfile-v0
> chore: remove `DOCKER_BUILDKIT` var

- .github/workflows/bioconda.yml
- .github/workflows/builder-docker-image.yml
- .github/workflows/cli.yml
- .github/workflows/web.yml
- cliff.toml
- docs/assets/release-instructions.md
Commit messages were missing from the body of GitHub release message. This attempts to fix that.
I also cleaned up formatting and clarified the "instrcutions" section text, while we are at it.
> fix: commit messages section in GitHub Releases

- packages_rs/nextclade-web/src/components/SequenceView/PeptideView.tsx
The UI calculations were using nuc length of a gene, where there should be aa length. This led to wrong right boundary on 3' unsequenced range displayed in peptide views (e.g. above 3000 for gene S in SC2, while the gene is only 1200-something long)
In this fix, I ensure that `geneLength` is counted in codons, not nucs.
Before:
After:
> fix(web): length of 3' unsequenced aa ranges

- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
- packages_rs/nextclade-web/src/wasm/analyze.rs
- packages_rs/nextclade/src/run/nextclade_run_one.rs
- packages_rs/nextclade/src/types/outputs.rs
Followup of https://github.com/nextstrain/nextclade/pull/1122
Introduces a CLI flag `--include-nearest-node-info` and the correponding internal parameter for Nextclade runs. Skips the `.nearestNodes` field in JSON/NDJSON unless this flag is present.
This parameter is always `false` in web, so this data is never included into the outputs of the web app. This also helps to slightly reduce the amount of data passed between webworkers
> feat: only emit nearest node info if a CLI flag is set

- packages_rs/nextclade/src/tree/tree_attach_new_nodes.rs
This adds custom phenotype values (such as `ace2_binding` and `"immune_escape"`) to the newly placed tree nodes.
They were previously missing, even though the technically similar clade-like node attributes were set. Which makes it somewhat asymmetric. 
I think it was simply an omission when the phenotype values were added.
Here I add the `phenotype_values` to the node similarly to how the `custom_node_attributes` are added.
This allows to see the values and colorings for phenotype values (if they are present in the dataset) on the tree page:
> fix: ensure phenotype values are attached to new tree nodes

- CHANGELOG.md
- packages_rs/nextclade/src/tree/tree.rs
- packages_rs/nextclade/src/tree/tree_attach_new_nodes.rs
- packages_rs/nextclade/src/tree/tree_find_nearest_node.rs
This feature improves the placement of sequences that
could be added to multiple nodes on the tree
with the same distance
As tie-braker we use "priors", a number that is present on every tree node
That number represent an a priori likelihood
that sequences attach to that node
The calculation details of this prior could change. All that matters for now
is the ordering of priors
The numerical value has no purpose (yet)
In the future, we intend to use the priors
to display placement confidence information.
This feature should be backwards compatible. Trees without priors should work just as before.
This commit is a placement-only subset of PR #1114
Priors need to be a float with path `node_attrs.placement_prior.value` - they should be on log10 scale (so -2 to mean 0.01).
For SARS-CoV-2, the …
> feat: use placement priors as tie breaker

- CHANGELOG.md
- packages_rs/nextclade-web/src/components/Common/MutationBadge.tsx
The `pos` of  `0` caused to show mutation badges with position 0, while they are supposed to be 1-indexed. This was due to incorrect conversion of `0` to `false`.
Here I fix the problem by using the explicit comparison to `undefined` and `null` (using the helper function `isNil()` from `lodash`), which avoids implicit conversions.
> fix: incorrect 0 coercion

- docker/docker-dev.dockerfile
There seems to be an issue (or an expected change) in wasm-pack 0.11.0: https://github.com/rustwasm/wasm-pack/issues/1062, where a path to`wasm-opt` is not detected correctly. This [breaks our build](https://github.com/nextstrain/nextclade/actions/runs/4474405842/jobs/7862840403). Everything seems to be working well on wasm-pack 0.10.3, so let's freeze the version for the time being.
> chore(ci): fix wasm CI build

- packages_rs/nextclade-cli/src/cli/nextalign_ordered_writer.rs
- packages_rs/nextclade-cli/src/cli/nextclade_ordered_writer.rs
This changes gene warnings severity to info. As discussed on Slack, there are many cases where missing genes is not a problem, notably in case of partial sequences. This is to declutter the logs - warning is the default severity. Info is opt-in.
> feat(cli): change gene warnings severity to info

- tests/run-smoke-tests
Related to: https://github.com/nextstrain/nextclade_data/issues/69, https://github.com/nextstrain/nextclade_data/pull/70
We missed a dataset bug where the dataset could not be fetched if the default ref is requested (by not providing `--reference` arg to `dataset get` command).
In order to catch this kind of issues on Nextclade level, here I added smoke tests which run `dataset get` without `--reference` arg for each of the available datasets.
The test currently fails, until the fix in https://github.com/nextstrain/nextclade_data/pull/70 is merged and deployed.
> test: add smoke tests for datasets with default refs

- scripts/publish_bioconda
Resolves CI failure: https://github.com/nextstrain/nextclade/actions/runs/4540204046/jobs/8000992798
Bioconda publish action is throwing the following error on `git push`:
```
+ git add recipes/nextalign/meta.yaml
+ git commit --quiet -m 'Update nextclade and nextalign to 2.13.1'
+ git push --quiet --set-upstream nextstrain bump/nextclade-2.13.1
To https://github.com/nextstrain/bioconda-recipes
! [remote rejected]       bump/nextclade-2.13.1 -> bump/nextclade-2.13.1 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/CommentResponder.yml` without `workflow` scope)
```
When a PR is crated it's created from the `master` branch of a fork to the `upstream/master`. The fork's `master` branch is likely out of date and even though we only modify 1 file, the …
> chore: fix CI failure when publishing to bioconda

- scripts/publish_bioconda
Reverts and replaces #1135
Resolves CI failure: https://github.com/nextstrain/nextclade/actions/runs/4540204046/jobs/8000992798
Bioconda publish action is throwing the following error on `git push`:
```
+ git add recipes/nextalign/meta.yaml
+ git commit --quiet -m 'Update nextclade and nextalign to 2.13.1'
+ git push --quiet --set-upstream nextstrain bump/nextclade-2.13.1
To https://github.com/nextstrain/bioconda-recipes
! [remote rejected]       bump/nextclade-2.13.1 -> bump/nextclade-2.13.1 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/CommentResponder.yml` without `workflow` scope)
```
When a PR is crated it's branch created from the `master` branch of a fork (remote `nextstrain`) to the `master` branch of the upstream (remote `upstream`). …
> chore: update master branch of the fork before making bioconda PR branch

- docs/dev/developer-guide.md
Had issues during the `wasm-pack` step on my M1 mac, it failed with `error: failed to build archive: section too large`
Solution found here: https://github.com/rust-bitcoin/rust-secp256k1/issues/283#issuecomment-1200858455
Adding it to docs, mostly for my future self as I think I'm the only one on mac right now (hiding behind `<details>`)
> docs(dev): Add steps for macOS (llvm and env vars)

- .github/workflows/bioconda.yml
- .github/workflows/builder-docker-image.yml
- .github/workflows/cli.yml
- .github/workflows/web.yml
- docker-dev
- docker/docker-dev.dockerfile
The main debian 9 (stretch) deb repos have been turned off, giving us docker build errors on CI when installing packages via apt-get.
Here I migrate to the deb archive repos, by replacing the contents of `/etc/apt/sources.list` with this:
```
deb http://archive.debian.org/debian/ stretch main non-free contrib
deb http://archive.debian.org/debian-security/ stretch/updates main non-free contrib
```
Additionally:
- Let's make CI builds more verbose (controllable by `VERBOSE=1` env var)
- Let's create docker buildx cache directory in advance to avoid missing directory warnings and to make sure the local cache works as expected.
> chore(ci): fix aarch64-unknown-linux-gnu builds

- tests/test-linux-distros
The docker image for RHEL 7 is no longer available:
```
Error response from daemon: unauthorized: access to the requested resource is not authorized
Failed running '/nextclade dataset list >/dev/null' on 'registry.access.redhat.com/ubi7/ubi'
Unable to find image 'registry.access.redhat.com/ubi7/ubi:latest' locally
docker: Error response from daemon: unauthorized: access to the requested resource is not authorized.
```
https://github.com/nextstrain/nextclade/actions/runs/4875338410/jobs/8698664297
So let's remove it
> chore(ci): remove rhel 7 from linux repo compat list

- tests/run-smoke-tests
Ensure that there is no duplicate combinations of dataset names and dataset references, to avoid parallel runs to overwrite dataset files while another is reading them.
> chore(ci): fix smoke tests

- .github/workflows/cli.yml
- .github/workflows/web.yml
Let's save some electricity by limiting actions on 'push' event only to main branches, to avoid the duplicated runs in each pull requests - for 'push' and for 'pull_request' event.
> chore(ci): prevent duplicated github action runs in pull requests

- packages_rs/nextclade-web/src/components/Results/ResultsTable.tsx
- packages_rs/nextclade-web/src/helpers/sortResults.ts
- packages_rs/nextclade-web/src/state/results.state.ts
Resolves https://github.com/nextstrain/nextclade/issues/1143
The `undefined` values are not comparable to strings, so Cornelius felt that in presence of empty values in custom clade-like columns the table sort misbehaves.
Here I treat the `undefined` values in custom clade-like columns and for phenotype columns as empty strings before sorting them. This way they can be sorted lexicographically along with other string values.
This may or may not what we want, but let's give it a try.
> fix(web): sort empty values

- packages_rs/nextclade-web/config/next/next.config.ts
- packages_rs/nextclade-web/config/next/withAppJson.ts
- packages_rs/nextclade-web/package.json
- packages_rs/nextclade-web/src/components/Layout/LayoutMain.tsx
- packages_rs/nextclade-web/src/components/Layout/LayoutResults.tsx
- packages_rs/nextclade-web/src/components/Layout/UpdateNotification.tsx
- packages_rs/nextclade-web/src/helpers/useAxiosQuery.ts
- packages_rs/nextclade-web/src/pages/_app.tsx
- packages_rs/nextclade-web/src/state/settings.state.ts
- packages_rs/nextclade-web/src/theme.ts
Related to: https://github.com/nextstrain/nextclade/issues/1139 https://github.com/nextstrain/nextclade/pull/1147
This PR introduces a notification toast which is displayed to the user when a new version of Nextclade Web is released. User can:
- accept the update - this simply hard-reloads the page and, thus, loads the new version of the app
- dismiss the notification - this hides the notification until the next version is available
- read changelog - this opens changelog document on GitHub (the new changelog markdown is not yet available in the old app, so we cannot render it nicely and we link to GitHub instead)
The version info is fetched from the server as a field in the new file, `app.json` which is created by webpack and placed into the webroot. The version in this file (always …
> feat(web): notify user on Nextclade Web updates

- packages_rs/nextclade-web/src/components/Main/DatasetCurrent.tsx
- packages_rs/nextclade-web/src/components/Main/DatasetSelector.tsx
- packages_rs/nextclade-web/src/components/Main/MainInputForm.tsx
- packages_rs/nextclade-web/src/i18n/resources/ar/common.json
- packages_rs/nextclade-web/src/i18n/resources/de/common.json
- packages_rs/nextclade-web/src/i18n/resources/el/common.json
- packages_rs/nextclade-web/src/i18n/resources/en/common.json
- packages_rs/nextclade-web/src/i18n/resources/es/common.json
- packages_rs/nextclade-web/src/i18n/resources/fa/common.json
- packages_rs/nextclade-web/src/i18n/resources/fr/common.json
- packages_rs/nextclade-web/src/i18n/resources/he/common.json
- packages_rs/nextclade-web/src/i18n/resources/hi/common.json
- packages_rs/nextclade-web/src/i18n/resources/id/common.json
- packages_rs/nextclade-web/src/i18n/resources/it/common.json
- packages_rs/nextclade-web/src/i18n/resources/ja/common.json
- packages_rs/nextclade-web/src/i18n/resources/ko/common.json
- packages_rs/nextclade-web/src/i18n/resources/nl/common.json
- packages_rs/nextclade-web/src/i18n/resources/pt/common.json
- packages_rs/nextclade-web/src/i18n/resources/ru/common.json
- packages_rs/nextclade-web/src/i18n/resources/ta/common.json
- packages_rs/nextclade-web/src/i18n/resources/th/common.json
- packages_rs/nextclade-web/src/i18n/resources/tr/common.json
- packages_rs/nextclade-web/src/i18n/resources/ur/common.json
- packages_rs/nextclade-web/src/i18n/resources/vi/common.json
- packages_rs/nextclade-web/src/i18n/resources/zh/common.json
- packages_rs/nextclade-web/src/io/fetchDatasets.ts
- packages_rs/nextclade-web/src/io/fetchDatasetsIndex.ts
- packages_rs/nextclade-web/src/state/dataset.state.ts
- packages_rs/nextclade-web/src/styles/_variables.scss
Resolves https://github.com/nextstrain/nextclade/issues/1139
This attempts to resolve situations described in the linked issues, when the new datasets are not available for users with stale browser tabs and also unless they switch the current dataset periodically.
To mitigate this, I add 2 kinds of data updates:
- Re-fetch dataset index and silently update the list of pathogens
- Check current dataset against the local list of datasets, and notify user when there is an update
Both updates are happening every time when:
- User visits for the first time
- The new tab is opened
- The browser tab with Nextclade Web is focused
- User navigates between pages
Additionally, these updates also happen periodically:
- index re-fetch every 12 hours (there is a network request for index file)
- …
> Avoid stale datasets in Nextclade Web

- packages_rs/nextclade-web/src/components/Layout/UpdateNotification.tsx
- packages_rs/nextclade-web/src/helpers/useAxiosQuery.ts
- packages_rs/nextclade-web/src/io/fetchDatasets.ts
These are meant to be checks performed in background, so let's ignore any failures, for example when network is disconnected. Update will be done when network connection is available again.
Tweak time intervals between update checks. We don't want these checks to put burden on users' computers,k especially on laptop batteries.
> fix(web): prevent crash when app.json or dataset cannot be fetched

- packages_rs/nextclade-web/src/components/Layout/UpdateNotification.tsx
- packages_rs/nextclade-web/src/io/fetchDatasets.ts
The main page blinks when selecting dataset, because at this point background update fetches are running, triggering React Suspense.
In this case we don't need to block the UI with suspense though, because these are background checks and their results are deferred to later time.
So let's disable suspense for the background checks for: 
- dataset index update
- current dataset version update
- software update
> fix(web): prevent main page from blinking when selecting dataset

- packages_rs/nextclade-web/src/components/Main/DatasetCurrent.tsx
Current dataset update notification did not disappear after "Update" button is clicked.
This required to make another current dataset version check, triggered e.g. by unfocusing then focusing window or waiting until the next scheduled check.
In this PR I forcibly dismiss notification when button is clicked.
> fix(web): correctly dismiss dataset update notification

- packages_rs/nextclade/src/analyze/aa_changes.rs
- packages_rs/nextclade/src/analyze/find_aa_motifs.rs
- packages_rs/nextclade/src/analyze/find_aa_motifs_changes.rs
- packages_rs/nextclade/src/analyze/letter_ranges.rs
- packages_rs/nextclade/src/io/fasta.rs
- packages_rs/nextclade/src/io/gene_map.rs
- packages_rs/nextclade/src/io/nextclade_csv.rs
- packages_rs/nextclade/src/qc/qc_rule_stop_codons.rs
- packages_rs/nextclade/src/run/nextalign_run_one.rs
- packages_rs/nextclade/src/run/nextclade_run_one.rs
- packages_rs/nextclade/src/translate/aa_alignment_ranges.rs
- packages_rs/nextclade/src/translate/translate_genes.rs
- packages_rs/nextclade/src/translate/translate_genes_ref.rs
- packages_rs/nextclade/src/tree/tree_preprocess.rs
The structs for translated genes and CDSes also contain copies (the .clone() is called on construction) of their corresponding gene and CDS annotations (from gene map). This is unnecessary in many cases - only the names and strands are accessed. Let's try to shave off a few microseconds of runtime by removing these clones.
> perf: avoid extra copies of genes and cdses

- packages_rs/nextclade/src/align/gap_open.rs
- packages_rs/nextclade/src/analyze/aa_changes.rs
- packages_rs/nextclade/src/analyze/nuc_del.rs
- packages_rs/nextclade/src/gene/cds.rs
- packages_rs/nextclade/src/translate/coord_map.rs
- packages_rs/nextclade/src/translate/coord_map2.rs
- packages_rs/nextclade/src/utils/range.rs
a range on a cds can span multiple segments of the cds
and thus can potentially map to multiple ranges in the global
reference sequence. This adds a function that walks along the
cds and determine the intersection with the range and the segments
> Add mapping from cds range to reference ranges

- packages_rs/nextclade/src/align/insertions_strip.rs
- packages_rs/nextclade/src/run/nextclade_run_one.rs
Stripped ref is the same as the original red, so this is redundant.
> perf: avoid calculating stripped ref sequence

- packages_rs/nextclade-web/src/components/SequenceView/SequenceSelector.tsx
- packages_rs/nextclade-web/src/helpers/number.ts
Each entry in the dropdown menu is now denoted with its feature type.
The menu now shows a hierarchy of gene-CDS relationships if a gene contains more than one CDS. Otherwise it's a flat list as before.
Currently, only CDS entries can be selected, because we don't have anything to show for other types of features. But in theory, any entry can be selected if needed.
We can use this new widget to display arbitrary trees of genetic features. For example, we can nest  proteins under CDSes.
More details can be displayed, e.g. frame, phase, length and boundaries of each feature etc.
> feat(web): reimplement gene selector in results table

- packages_rs/nextclade/src/align/align.rs
- packages_rs/nextclade/src/align/seed_match2.rs
extend_seed now determines the longest matching stretch in the last window and will terminate the seed match after that stretch.
There is substantial duplication here for forward and backward extension with the only difference that in one case we are incrementing `length` and looking up `ref_seq[ref_pos + length]` and  `qry_seq[qry_pos + length]` and in the other case `ref_seq[ref_pos - 1]` and  `qry_seq[qry_pos - 1]`.
as for tests, this function can be readily tested. for an input:
```
seed = {ref_pos: 40, qry_pos: 38; length: 10, }
//                                                |---------|
ref_seq = "CGCATCGCTGATCGTACGATCGTACTGGTACTGCACTCTAAAAAAAAAACGTGCTGACTGCACTGCATTTATACGATTCTCTCTTCCGACTGTCGACTG";
qry_seq =    "TCGCTGATCGTACGATCCGTACTGGTACTGCACTCAAAAAAAAAAAGGTGCTGACTGCACTGCATTTATAG …
```
> feat: improve cropping of extended seeds

- packages_rs/nextclade/Cargo.toml
This adds "static" feature for xz2 and bzip2 crates to ensure we don't depend on any system libraries.
> fix: avoid dependency on sys libs for xz2 and bzip2 crates

- packages_rs/nextclade/src/tree/tree_builder.rs
Addresses part of: https://github.com/nextstrain/nextclade/issues/1207
In corner cases, when a tree is small, consists of a single node or entirely empty, Nextclade would crash, because there were not enough guards when fetching non-existing parent nodes from the graph. In this case, once a root is reached, Nextclade would crash. This PR adds additional checks to prevent this from happening.
> fix: avoid crashes when there is no parent node

- packages_rs/nextclade/src/align/align.rs
- packages_rs/nextclade/src/align/score_matrix.rs
Historically, nextalign has aligned sequence around gaps on the right when there were equivalent gap placements and we introduced a flag to align left/right. The flag amounts to following a "match" or "gap" path first and algorithmically can be dealt with a `<` vs `<=` comparison of scores when evaluating options (pick first or last). Alas, this switch was not correctly implemented and likely resulted in suboptimal alignments for `--gap-alignment-side left`.
> fix: flag to align gaps left

- packages_rs/nextclade-cli/src/bin/featuretree.rs
- packages_rs/nextclade-cli/src/bin/genemap.rs
- packages_rs/nextclade-cli/src/bin/generate_jsonschema.rs
- packages_rs/nextclade-cli/src/cli/nextclade_dataset_list.rs
- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
- packages_rs/nextclade-web/src/wasm/analyze.rs
- packages_rs/nextclade-web/src/wasm/main.rs
- packages_rs/nextclade/src/io/json.rs
- packages_rs/nextclade/src/io/results_json.rs
Currently JSON being sent from wasm to js is prettified. This means more bytes are being sent across language boundaries and might cause unnecessary slowdown.
Here I am adding a function to serialize to JSON without prettifying it. Let's see if it has any visible effect on performance.
However it also means that the downloadable JSON is also minified. Or it will need to be prettified on demand.
> perf(web): send minified json between wasm and js

- packages_rs/nextclade/src/analyze/find_private_nuc_mutations.rs
- packages_rs/nextclade/src/analyze/is_sequenced.rs
- packages_rs/nextclade/src/run/nextclade_run_one.rs
Reported on Slack: https://neherlab.slack.com/archives/C015PFP5V44/p1690300205470069
There is a problem when searching for reversions.
Setup:
```
Nuc pos: 22770 (1-based)
Ref:  G
Node: A
Qry:  R
```
When searching for mutations, `R` is not considered a substitution. So when private mutations are searched it is not considered a mutated position. Next, when searching reversions, we see that the position is not mutated, but sequenced, so it is marked as a reversion.
This is wrong, because we cannot tell whether reversion have taken place or not, due to ambiguity.
Here I exclude all query positions with non-ACGTN from consideration.
Example bugged:
https://clades.nextstrain.org/?dataset-name=sars-cov-2&input-tree=https://nextstrain.org/charon/getDataset?prefix=staging/nextclade/sars-cov-2&inpu …
> fix: don't consider ambiguous nucs for reversions

- packages_rs/nextclade/src/io/concat.rs
- packages_rs/nextclade/src/io/fasta.rs
It was reported that when multiple fasta files are provided to Nextclade CLI, if some of the the files don't contain trailing newlines, the sequences aren't read correctly.
The issue comes from the fact that the `Concat` struct concatenates readers (e.g. files in this case) seamlessly, and last sequence of previous reader transitions immediately into the first sequence of the next reader. Then line parsing with `BufRead` cannot split these sequences, because there is no newline character between them.
To address this, here I modify `Concat` struct, adding an additional parameter `delimiter`. When provided, readers are concatenated by alternating with given delimiter bytes. In fasta reader this allows to force insertion of a "\n" character between readers.
If files contain newlines and/or …
> Fix reading fasta without trailing newline

- packages_rs/nextclade/src/tree/tree_builder.rs
when a samples shared all privated nuc mutations with a parent, we move up the tree and subtract the shared mutations. However, in rare cases when there are multiple mutations in a codon, not all amino acid mutations are shared. hence we still need to handle left over mutations also in the case where we just move up the tree, not only when we move down the tree.
This change actually harmonized cases and reduced code duplication.
> fix: double mutation in codon when moving up the tree

- packages_rs/nextclade/src/align/seed_match2.rs
Allowed mismatches were 1 smaller than intended when extending seeds due to `<` rather than `<=`
> Allowed mismatches were -1 too small due to < rather than <=

- packages_rs/nextclade/src/align/align.rs
- packages_rs/nextclade/src/align/seed_alignment.rs
reimplementation of https://github.com/nextstrain/nextclade/pull/1241
this still complains about potential uninitialized variable.
> fix: return best alignment when band extension hits max_band_limit

- packages_rs/nextclade/src/analyze/divergence.rs
- packages_rs/nextclade/src/run/nextclade_wasm.rs
- packages_rs/nextclade/src/tree/params.rs
- packages_rs/nextclade/src/tree/split_muts.rs
- packages_rs/nextclade/src/tree/tree_builder.rs
Followup of https://github.com/nextstrain/nextclade/pull/1249
Inspired by refactoring in [`15757ec` (#1249)](https://github.com/nextstrain/nextclade/pull/1249/commits/15757ece18f4e57931c27306e18c2ae229b2cfdb) I decided to continue, because the code in the `finetune_nearest_node()` can be clearly divided into independent functions.
Change of terminology, to clarify meaning of varables:
- `current_best_node` -> `best_node` (this is the loop's external state)
- `best_node` -> `candidate_node` 
- `best_split_result` ->  `candidate_split`
I tried to make commits to contain only 1 minimal change which compiles and runs. Plus there is a few pink elephants I encountered  - reported in the PR comments below.
> Refactor and cleanup tree finetuning code

- .github/ISSUE_TEMPLATE/config.yml
"vers" was added in a81376c09cba730024f399e9b7e21d6605fb5ff0, I'm assuming in error since it is not a documented value for the config file¹.
¹ https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> Fix issue template config

- .readthedocs.yml
Read the Docs will soon require the specification of a build OS in our configuration file [1] and have already started temporary enforcement of this requirement as a warning. This commit follows the example in the RTD docs for conda environments [2], adding a `build` block using the latest supported Ubuntu and mambaforge.
[1] https://blog.readthedocs.com/use-build-os-config/
[2] https://docs.readthedocs.io/en/stable/config-file/v2.html#conda
> docs: Specify Read the Docs build OS

- packages_rs/nextclade-cli/src/cli/nextclade_seq_sort.rs
The `nextclade sort` subcommand have been duplicating duplicate output sequences, one for each dataset suggestion, due to invalid calculation of possible dataset name prefixes. Here I fix that.
> fix(cli): prevent sort command from generating duplicate sequences

- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-web/src/components/FilePicker/FilePickerAdvanced.tsx
- packages_rs/nextclade-web/src/components/SequenceView/PeptideView.tsx
- packages_rs/nextclade/src/align/align.rs
- packages_rs/nextclade/src/run/nextclade_wasm.rs
Renames the following concepts in the visible parts of the software: strings in the UI, text messages, CLI args etc.
- genemap -> genome annotation
- virus properties -> pathogen.json
- root sequence -> reference sequence
Note that project code (e.g. types and variable names) still largely contains old names. This would be a large refactor and might introduce bugs, so I see no immediate advantage there.
> feat: rename old concepts

- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_dataset_get.rs
- packages_rs/nextclade-cli/src/cli/nextclade_dataset_list.rs
- Add error message for removed `--input-virus-properties`, `--input-root-seq`, `--reference`, `--input-gene-map`, `--genemap`
- Deduplicate error messages text.
- Group deprecated args in one place
> fix(cli): correctly deprecate input args

- packages_rs/nextclade-web/src/components/SequenceView/SequenceMarkerAmbiguous.tsx
- packages_rs/nextclade-web/src/components/SequenceView/SequenceView.tsx
- packages_rs/nextclade-web/src/components/Settings/SeqViewSettings.tsx
- packages_rs/nextclade-web/src/helpers/getNucleotideColor.ts
- packages_rs/nextclade-web/src/state/seqViewSettings.state.ts
Resolves: https://github.com/nextstrain/nextclade/issues/700
Add colored markers for ambiguous (non-ACTGN) nucleotides to nucleotide sequence view.
I tried to pick colors to be pale (so that they resemble pale grey of missing nucs) and to be a mixture of colors of corresponding disambiguated characters, or to be inverse color in case of "not" characters (e.g. color of not-A is a pale inverse of color of A).
I made markers half-height at the top by default, just like missing nucs. (Settings UI is currently broken, so it's impossible to change at the moment, sorry)
Tooltip text is as specified in the original issue.
> feat(web): add sequence markers for ambiguous nucleotides

- packages_rs/nextclade-web/src/components/SequenceView/SequenceSelector.tsx
A more accurate term, by request from scientists
> fix(web): rename "Full genome" to "Nucleotide sequence"

- packages_rs/nextclade-web/src/components/Tree/TreePage.tsx
- packages_rs/nextclade-web/src/components/Tree/TreePageContent.tsx
- packages_rs/nextclade-web/src/pages/tree.tsx
When loading for the first time the `/tree` page  shows blank space without even navbar and footer. This is due to dynamic loading of the page content.
Here I:
- bubble the `Layout` component from tree page one level up, out of dynamically loaded chunk, so that navbar and footer are static and displayed at all times
-  add `loading` parameter to `dynamic()` call, such that the loading spinner is displayed during page fetching
The page still freezes after fetching, while the tree is rendered. I believe this is due to the sheer amount of things being rendered in Auspice, but might also be perf problems on Nextclade side. I don't currently know a way to handle this or how to display loading indicator there, because React rendering is still synchronous and blocks main thread.
> fix(web): prevent tree page from showing blank screen

- packages_rs/nextclade-web/src/components/Layout/Footer.tsx
- packages_rs/nextclade-web/src/components/Layout/Layout.tsx
- packages_rs/nextclade-web/src/components/Tree/TreePageContent.tsx
Adds small padding for tree filter text, increases z-index of header and footer so that their shadow is always above the tree page svg components.
> fix(web): tree styles

- packages_rs/nextclade-web/src/components/Main/DatasetSelectorList.tsx
This will also take into account reference friendly names when filtering dataset selector list
> feat(web): search ref names in dataset selector

- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_dataset_list.rs
- tests/run-smoke-tests
Let's invert the boolean flags `--include-community` and `--include-experimental` to --no-community and `--no-experimental` in `dataset list` command.
This way community and experimental will be shown by default, additionally promoting their use, increase probability of user feedback and improvements.
> feat(cli): invert --include-community and --include-experimental flags

- packages_rs/nextclade-web/src/hooks/useRunAnalysis.ts
This correctly resets currently viewed gene state when a new run is initialed. This prevents the genome annotation widget from trying to lookup a CDS from the previous pathogen.
> fix(web): prevent 'CDS not found' error

- packages_rs/nextclade-web/src/styles/_variables.scss
Adjust bootstrap theme's line weight for all text and separately for headings to match the currently used font.
This prevents headings from having additional spacing (non-margin, non-padding) at the bottom, due to excessive line height, and makes alignment of neighboring inline elements easier.
> fix(web): adjust typography

- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
- packages_rs/nextclade-cli/src/dataset/dataset_download.rs
- packages_rs/nextclade-web/src/hooks/useExportResults.ts
- packages_rs/nextclade/src/gene/gene_map.rs
- packages_rs/nextclade/src/io/fasta.rs
- tests/run-smoke-tests
Attempts to remove inconsistencies in naming and handling of genes and CDSes, to reflect changes in how genome annotations are handled in v3.
In Nextclade v2 there were only genes, so in Nextclade CLI `--genes` argument and `{gene}` placeholder in `--output-translations` make sense.
In Nextclade v3 there are genes and CDSes involved and CDSes have central place - they are now what's need to be selected by the `--gene` arguments and the CDS name needs to be substituted where the `{gene}` variable was.
So in this PR, at the very minimum, I did:
- rename `--genes` to `--cds-selection` (initially `--cdses`, but Richard suggested `--cds-selection`)
- rename `{gene}` to `{cds}` in `--output-translations` template string
- change default value for `--output-translations` template string from …
> Consistent usage of gene vs CDS in the interface

- packages_rs/nextclade-web/src/io/fetchSingleDatasetFromUrl.ts
Examples:
- Local server: https://nextclade-git-fix-web-dataset-url-nextstrain.vercel.app/?dataset-url=http://localhost:3001&input-fasta=example
- GitHub full URL: https://nextclade-git-fix-web-dataset-url-nextstrain.vercel.app/?dataset-url=https://github.com/nextstrain/nextclade_data/tree/master/data/nextstrain/zika/KX369547.1&input-fasta=example
- GitHub shortcut: https://nextclade-git-fix-web-dataset-url-nextstrain.vercel.app/?dataset-url=gh:nextstrain/nextclade_data/data/nextstrain/zika/KX369547.1&input-fasta=example
> fix(web): make URL parameter `dataset-url` work again

- docs/user/nextclade-cli/reference.md
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
Follow-up of #1298
Came across when I used `--genes` and got a wrong suggestion from clap (`--genemap`).
Tested:
```
./bin/nextclade run             results/all-clades/filtered.fasta             --retry-reverse-complement             --input-ref resources/all-clades/reference.fasta             --excess-bandwidth 100             --terminal-bandwidth 300             --allowed-mismatches 8             --window-size 40             --min-seed-cover 0.1             --input-annotation resources/genome_annotation.gff3             --gap-alignment-side left             --output-fasta results/all-clades/aligned.fasta             --include-reference             --genes NBT03_gp052,NBT03_gp174,NBT03_gp175,OPG001_dup,OPG002_dup,OPG003_dup,OPG001,OPG002,OPG003,OPG005,OPG015,OPG019,OPG021,OPG022,OPG023,OP …
```
> feat: warn user about `--genes` -> `--cdses` renaming

- packages_rs/nextclade-cli/src/cli/nextclade_dataset_get.rs
- packages_rs/nextclade-cli/src/cli/nextclade_dataset_list.rs
- packages_rs/nextclade-cli/src/dataset/dataset_download.rs
- packages_rs/nextclade-cli/src/dataset/dataset_table.rs
- packages_rs/nextclade-web/src/components/Main/DatasetSelectorList.tsx
- packages_rs/nextclade-web/src/io/fetchDatasetsIndex.ts
- packages_rs/nextclade/src/analyze/virus_properties.rs
- packages_rs/nextclade/src/io/dataset.rs
Sibling PR in data: https://github.com/nextstrain/nextclade_data/pull/116 (can be merged independently; no breakage)
This allows to use shortcuts instead of full paths for datasets containing `shortcuts` array in their `pathogen.json`:
CLI example:
```bash
nextclade run --dataset-name='sc2'
nextclade dataset list --name='sc2'
nextclade dataset list --search='sc2'
nextclade dataset get --name='sc2'
```
Web example:
https://nextclade-git-feat-dataset-name-shortcuts-nextstrain.vercel.app/?dataset-name=sc2
(these examples assume that there is a dataset which defines a shortcut `sc2`; in PR https://github.com/nextstrain/nextclade_data/pull/116 this is `nextstrain/sars-cov-2/MN908947`)
> Add dataset name shortcuts

- packages_rs/nextclade-web/src/constants.ts
- packages_rs/nextclade-web/src/io/fetchDatasets.ts
- packages_rs/nextclade-web/src/io/fetchSingleDatasetFromGithub.ts
This allows to use GitHub shortcuts with only branch specified:
```
?dataset-server=gh:@my-branch@
```
In this case, it assumes official data repo (`nextstrain/nextclade_data`) and the default path (`/data_output`) in it.
> feat(web): default to official repo and path when omitted from url param

- packages_rs/nextclade-web/src/components/Main/DatasetInfo.tsx
- packages_rs/nextclade-web/src/components/Main/MainInputForm.tsx
- packages_rs/nextclade-web/src/components/Main/QuerySequenceList.tsx
Prevents text on main page from overflowing when datasets contain excessively long field values.
> fix(web): improve long text fit in the ui

- packages_rs/nextclade-web/src/components/Main/ExampleSequencePicker.tsx
This hides datasets which don't have example fasta files from the "Examples" list
> fix(web): remove non-existent example fasta from dropdown

- packages_rs/nextclade-web/src/components/Layout/NavigationMenu.tsx
The error was:
> `li` cannot be child of `li`
this was due to a missing wrapper `ul` in the menu,
> fix(web): fix html nesting error in nav menu

- packages_rs/nextclade-web/src/components/Main/MainInputForm.tsx
This avoids second redundant run of dataset auto-suggest when navigating to dataset page and when auto-suggest is already running
> fix(web): don't start another run of autosuggest if already running

- packages_rs/nextclade-web/src/components/Layout/Footer.tsx
I noticed that the logos were not centered. This PR might fix that.
Before (black line is centered):
After:
I think it's better
> fix(web): center logos in footer div

- packages_rs/nextclade-web/src/components/Common/BrowserWarning.tsx
The reason we deprecated Safari was that it didn't support shared web workers Since v16.0 shared web workers are supported so we no longer need to show the browser warning  Alternatively, we could discourage less loudly, saying that Safari is not tested (for >=16) while still erroring for lower versions.
> feat(web): Support Safari >= 16.0 again

- packages_rs/nextclade-web/src/components/Results/ResultsFilter.tsx
> fix(web): styling of results table filter panel

- packages_rs/nextclade-web/src/components/GeneMap/GeneMap.tsx
When we have no CDS, we currently throw an error in web.
Test e.g. via:
https://nextclade-git-cds-error-nextstrain.vercel.app/?dataset-server=gh:@scratch@&dataset-name=nextstrain/scratch/reference-only
> fix(web): don't throw error if there's no CDS

- packages_rs/nextclade-cli/src/dataset/dataset_table.rs
The column was always empty. This will yield some more space for more important columns.
> feat(cli): remove `authors` column from `dataset list` table

- scripts/publish_bioconda
Nextalign binaries are no longer produced in v3, so here I remove any mentions of Nextalign from bioconda packaging CI workflow.
This means that Nextalign Conda package will no longer be published and will stay forever on v2 (version 2.14.0). This may or may not be what we want.
> chore(ci): remove Nextalign conda packaging from CI

- data/README.md
- data/sars-cov-2/README.md
- packages_rs/nextclade-web/src/components/About/AboutContent.mdx
- packages_rs/nextclade-web/src/components/Layout/NavigationBar.tsx
- packages_rs/nextclade-web/src/components/Main/Downloads.tsx
Thanks to @Mike-Honey for reporting at https://discussion.nextstrain.org/t/cli-link-broken-from-clades-nextstrain-org/1528
Fixed with the following command (might be useful for similar renames):
```bash
OLD=https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-cli.html
NEW=https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-cli/index.html
rg -l "$OLD" | xargs sed -i "s|$OLD|$NEW|g"
```
> fix: correct CLI links to point to new index.html

- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- test-datasets
Noticed this in the `--help` string
> chore: replace 2 leftovers from {gene} -> {cds} conversion

- CHANGELOG.md
- docs/user/migration-v3.md
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
It seems that this line should have been removed in https://github.com/nextstrain/nextclade/pull/1298
but this was forgotten.
The default path will now be `nextclade.cds_translation.{cds}.fasta` as Richard suggested in
https://github.com/nextstrain/nextclade/pull/1298#issuecomment-1786602733
Before this PR it was (wrongly) `nextclade.cds_translation.{cds}.fasta.translation.fasta` since v3 release.
The default output path rename is a v3 breaking change that we don't seem to have documented yet. How shall we best do this given that v3.0.0 is already out? Post hoc editing changelog and adding to migration docs? Or do you prefer something else @ivan-aksamentov?
> fix: remove extra "translations.fasta" in default output translation path

- packages_rs/nextclade-cli/src/cli/nextclade_dataset_get.rs
- packages_rs/nextclade/src/io/dataset.rs
This avoids `nextclade dataset get` failure reported here: https://github.com/nextstrain/nextclade_data/issues/136#issuecomment-1915476754
The meaningless check `.is_latest()` was left over from the time when each dataset version was a separate object. Now each datasets contain a list of all versions inside of it, so it does not make sense to filter latest datasets. Curiously, it was still working until now, when datasets has got than one version in the array (die to the second release of RSV datasets today).
> fix(cli): `dataset get` for datasets with multiple versions

- .github/workflows/cli.yml
Fix CI error
```
Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
Example: https://github.com/nextstrain/nextclade/actions/runs/7742331041/job/21111396773?pr=1398#step:14:16
This is due to changes in `actions/upload-artifact@v4`. We recently upgraded it from `v3`  (see commit 24b4ea8a091718c40fab79ee0aee738d4b834e79). Now once an artifact is uploaded in one matrix job, the subsequent uploads with the same name from other jobs fail.
To resolve this, I add matrix value to the artifact name and when downloading these artifacts later, I download them by wildcard pattern and merge them.
The solution is from here: https://github.com/actions/upload-artifact/issues/478#issuecomment-1918746908
> chore(ci): fix error in `actions/upload-artifact@v4`

- docs/user/nextclade-cli/reference.md
- packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
- packages_rs/nextclade-cli/src/cli/nextclade_loop.rs
- packages_rs/nextclade-cli/src/dataset/dataset_download.rs
- packages_rs/nextclade-web/src/build.rs
- packages_rs/nextclade-web/src/wasm/main.rs
- packages_rs/nextclade/src/analyze/mod.rs
- packages_rs/nextclade/src/analyze/pcr_primer_changes.rs
- packages_rs/nextclade/src/analyze/pcr_primers.rs
- packages_rs/nextclade/src/analyze/virus_properties.rs
- packages_rs/nextclade/src/run/nextclade_run_one.rs
- packages_rs/nextclade/src/run/nextclade_wasm.rs
Resolves: https://github.com/nextstrain/nextclade/issues/1388
Brings back a possibility to use`primers.csv` file and calculate PCR primer mutations in Nextclade CLI v3, just like in Nextclade v2.
What's done:
What it does not do:
- unlike Nextclade v2, this version does not read `primers.csv` file from a dataset
- Nextclade Web does not use primers at all - an empty array of primers is always passed into the algorithm
> feat(cli): bring back PCR primers

- packages_rs/nextclade-web/src/components/Results/ResultsTableRowResult.tsx
Ensure results table row colors always alternating and look like zebra stripes, regardless of sorting or filtering applied to the rows.
> fix(web): ensure table stripes are always alternating

- packages_rs/nextclade-cli/src/cli/nextclade_seq_sort.rs
This allows to unambiguously and reliably map entries in the input fasta to the entries in the output tsv, which is important in presence of duplicated sequence names.
> feat: add index column to the tsv output of sort subcommand 

- docs/user/nextclade-cli/usage.md
Fixing broken links I noticed when reading through the Nextclade CLI usage page.
> docs: Fix links on Nextclade CLI usage page

- Cargo.toml
- packages/nextclade-cli/src/cli/nextclade_loop.rs
- packages/nextclade-cli/src/cli/nextclade_seq_sort.rs
- packages/nextclade-cli/src/dataset/dataset_download.rs
- packages/nextclade/src/align/backtrace.rs
- packages/nextclade/src/align/band_2d.rs
- packages/nextclade/src/align/score_matrix.rs
- packages/nextclade/src/align/seed_alignment.rs
- packages/nextclade/src/analyze/divergence.rs
- packages/nextclade/src/features/feature_group.rs
- packages/nextclade/src/features/feature_tree.rs
- packages/nextclade/src/features/feature_tree_format.rs
- packages/nextclade/src/io/file.rs
- packages/nextclade/src/io/gff3.rs
- packages/nextclade/src/io/nextclade_csv.rs
- packages/nextclade/src/io/results_json.rs
- packages/nextclade/src/qc/qc_rule_mixed_sites.rs
- packages/nextclade/src/run/nextclade_run_one.rs
- packages/nextclade/src/tree/tree_builder.rs
- packages/nextclade/src/utils/error.rs
- packages/nextclade/src/utils/global_init.rs
This re-enables lints `dead_code` and `unused_variables` and fixes the resulting warnings
> refactor: remove unused code

- packages/nextclade-cli/src/cli/nextclade_dataset_get.rs
- packages/nextclade-cli/src/cli/nextclade_dataset_list.rs
- packages/nextclade/src/io/dataset.rs
Partially addresses #175
The `--tag` argument have been filtering only by the latest tag. This correct the filtering logic, so that all version tags are considered when filtering.
> fix(cli): dataset tag not applied correctly in dataset cli commands

- packages/nextclade-cli/src/cli/nextclade_dataset_get.rs
- packages/nextclade-cli/src/cli/nextclade_dataset_list.rs
- packages/nextclade-cli/src/dataset/dataset_download.rs
- packages/nextclade/src/io/dataset.rs
- packages/nextclade/src/utils/string.rs
Followup of #1420
This restructures the filtering logic, such that it is now possible to emit correct and useful error messages when either requested dataset name or tag or both do not match what's available.
> fix(cli): correct error messages in `dataset get` and `dataset list`

- packages/nextclade-web/src/components/Common/BrowserWarning.tsx
Followup of https://github.com/nextstrain/nextclade/pull/1348
There are reports that WebWorkers don't work in Nextclade on Safari 16.3.
I was able to confirm that they do work on 16.5, so I am setting this version as the lowest supported. I don't have access to versions lower than that.
> feat(web): restrict Safari browser support to >= 16.5

- packages/nextclade-cli/src/dataset/dataset_download.rs
- packages/nextclade/src/utils/string.rs
We want to only read dataset files which are declared in the `pathogen.json`.Most of these files are optional and can be missing, so we should never rely on their presence or their particular names, without checking with what's declared in `pathogen.json`
However, in Nextclade CLI we've been reading hardcoded `tree.json` and `genome_annotation.gff3` whenever `--input-dataset` was given a dataset zip archive (as opposed to a dataset directory).
Let's made it to use `pathogen.json:files.treeJson` and `pathogen.json:files.genomeAnnotation`, just like it happens when using dataset in the form of directory, or like it happens in Nextclade Web.
While we are here, let's also improve error messages when reading zip archives.
> fix(cli): don't use hardcoded filenames when reading dataset zip

- scripts/publish_bioconda
- scripts/update-bioconda.py
Doing #1430 but now properly
It's a 2 line fix, just adding aarch64 to a list and a dict. I've tested it works and discovered a bug in our previous sha
This is the PR test: https://github.com/bioconda/bioconda-recipes/pull/47271
> Update aarch64 sha256sum in bioconda recipe as well

- packages/nextclade-cli/src/dataset/dataset_download.rs
- packages/nextclade/src/utils/fs.rs
- packages/nextclade/src/utils/mod.rs
For dataset authors It is hard to debug problems when:
-  a file is present in the dataset, but author forgot to declare it in pathogen.json
-  there is a typo in the file declaration in pathogen.json, so it is ignored by Nextclade
In both cases, Nextclade will ignore unknown entries and potentially miss a tree.json or a genome_annotation.gff3, which leads to missing the parts of the analysis - either clades and tree or translation and aminoacid mutations.
Let's add a check which warns Nextclade CLI users when they run with a dataset with either extra undeclared files or, conversely, when there's extra unknown files declared. This way authors can catch the mistakes early.
Example warning message:
```
When reading dataset from "dataset.zip": The following files are present in the dataset …
```
> feat(cli): warn on extra or undeclared dataset files

- packages/nextclade-web/src/components/Main/MainInputForm.tsx
- packages/nextclade-web/src/components/Main/SuggestionPanel.tsx
- packages/nextclade-web/src/hooks/useRunSeqAutodetect.ts
- packages/nextclade-web/src/state/autodetect.state.ts
This changes behavior of dataset suggestions: now when use clicks "Suggest" button on main page, if suggestion run completes successfully, then top matching dataset is selected as current dataset automatically. This does not happen after automatic suggestion runs.
> feat(web): select top dataset when suggest was triggered manually

- docs/user/datasets.md
Fixes a link to the older datasets directory on GitHub that now lives at the level just above where both "nextstrain" and "community" datasets can be browsed.
> Fix broken link to datasets list on GitHub

- packages/nextclade-web/src/state/dataset.state.ts
Resolves https://github.com/nextstrain/nextclade/issues/1450
This removes dataset path equality check preventing dataset object from being updated. The older dataset object version from local storage will then be used.
I don't remember why this check was needed. It seems overwriting current dataset is fine whether it's equal (by path or before paths were a thing using name/ref/tag). Hopefully this does not bring any undesired effects.
I consider this a short-term fix. A proper solution should probably remove storing dataset object in the local storage, but only storing a dataset identifier there. But ti's more involved and we need to figure out what generally identifies a dataset (dataset path, alright, but we can also have the same path on different dataset servers as well as single …
> fix(web): update current dataset when remote pathogen.json changes

- packages/nextclade-web/src/components/Results/ColumnClade.tsx
- packages/nextclade-web/src/filtering/filterByClades.ts
- packages/nextclade/src/io/nextclade_csv.rs
- packages/nextclade/src/run/nextclade_run_one.rs
- packages/nextclade/src/tree/tree.rs
- packages/nextclade/src/tree/tree_attach_new_nodes.rs
- packages/nextclade/src/tree/tree_find_nearest_node.rs
- packages/nextclade/src/types/outputs.rs
Not all trees have `clade_membership` attribute on the nodes. Here I made this attribute optional in Nextclade.
If `clade_membership` is not present:
- output JSON/NDJSON result entries will not contain `clade` field
- `clade` column in output CSV/TSV will be empty
- `clade` column in Nextclade Web will be empty
it does not affect any other parts of the application. Notably clade-like attributes (from `.meta.extensions.nextclade.clade_node_attrs` are still assigned and being written to the output).
Tested on `sars-cov-2` dataset and `clade_membership` node attribute removed using `jq`:
```bash
jq 'walk(if (type == "object" and .clade_membership) then del(.clade_membership) else . end )' tree.original.json > tree.json
```
(in real trees you might also need to change metadata, such as …
> feat: make `clade_membership` node attribute optional

- packages/nextclade-web/package.json
- packages/nextclade-web/src/io/axiosFetch.ts
- packages/nextclade-web/src/io/fetchSingleDatasetAuspice.ts
- packages/nextclade-web/src/styles/global.scss
- packages/nextclade-web/yarn.lock
Followup of https://github.com/nextstrain/nextclade/pull/1455
If `.root_sequence` is not available on Auspice JSON, let's attempt to fetch ref sequence from sidecar Auspice JSON. For that let's GET from the same URL, but with `Accept: application/vnd.nextstrain.dataset.root-sequence+json` header.
> feat: fetch sidecar Auspice JSON if `.root_sequence` is not on the tree

- packages/nextclade/src/graph/graph.rs
- packages/nextclade/src/graph/node.rs
- packages/nextclade/src/tree/tree.rs
Recursion has been overflowing call stack in the web app when very large trees are used.
Let's remove recursion when converting internal graph into Auspice JSON when writing out Auspice JSON tree. 
In this version I convert all nodes in advance, and store them in a map (which may or may not be needed) and then explore the tree using stack-based post-order traversal.
This should provide byte-equal JSONs when compared to the previous, recursive implementation.
> refactor: remove recursion when writing out Auspice JSON

- packages/nextclade-web/src/io/fetchDatasets.ts
- packages/nextclade-web/src/io/fetchSingleDatasetFromGithub.ts
When deciding whether a URL is a GitHub repo url, currently certain URLs trigger false positives.
For example, user attachments (`https://github.com/user-attachments/files/12345678/example.txt`), assets, gists, releases etc.
Let's exclude certain paths in regex from consideration.
Some of these paths don't respond with CORS headers, so they cannot be used in Nextclade anyways, but at least users will see a correct error message, rather than GitHub repo URL parsing error, which does not make sense for the URL types listed above.
P.S. I wish there would be a library for that, so that I don't need to write and maintain this... All we need is to download single files and directories from GitHub repos.
> fix(web): exclude selected GitHub URLs when checking for repo URL

- packages/nextclade-web/.eslintrc.js
- packages/nextclade-web/src/components/Main/SuggestionAlertMainPage.tsx
- packages/nextclade-web/src/io/fetchDatasets.ts
- packages/nextclade-web/src/io/fetchSingleDatasetAuspice.ts
- packages/nextclade-web/src/io/fetchSingleDatasetDirectory.ts
- packages/nextclade-web/src/io/fetchSingleDatasetFromGithub.ts
- packages/nextclade-web/src/pages/_app.tsx
- packages/nextclade/src/io/dataset.rs
When `dataset-json-url` param is used, the entire auspice json was stored in local storage. For large files this might be bigger than what browsers allow and the store operation would fail. Subsequent reads would retrieve either nothing or some fragment of data.
Here I add some logic to make sure we store auspice json in memory only. Sadly, this means that page reload wipes all the data and we currently don't have a good mechanism to store the previous dataset URL in order to re-fetch it. This will need to be implemented. Currently I opted for discarding the stored dataset if it was auspice dataset. This should be alright, as the feature was primarily designed to be used when navigating to Nextclade with url params set.
This PR only implements a workaround for something that's …
> fix(web): prevent writing large auspice json to local storage

- packages/nextclade/src/io/nextclade_csv.rs
Resolves: https://github.com/nextstrain/nextclade/issues/1459
Previously, Nextclade treated output CSV/TSV columns `index` and `seqName` as mandatory.
Here I make them optional. Users now can:
- in CLI: use `index` and `seqName` values in  `--output-columns-selection`
- in Web: tick checkboxes for `index` and `seqName` in "Column config" on export page
> feat: allow `index` and `seqName` in column selection

- packages/nextclade-cli/src/dataset/dataset_table.rs
- packages/nextclade/src/io/dataset.rs
Resolves: https://github.com/nextstrain/nextclade/issues/1458
Sibling in data: https://github.com/nextstrain/nextclade/pull/1473
This adds "capabilities" column to the console output of the `nextclade dataset list` command.
> feat(cli): display dataset capabilities in `dataset list` command

- packages/nextclade-cli/src/dataset/dataset_download.rs
- packages/nextclade/src/run/nextclade_wasm.rs
- packages/nextclade/src/tree/tree.rs
Following conversation in https://github.com/nextstrain/nextclade/pull/1455#issuecomment-2146589157
Let's add a warning if the reference sequence provided any of the possible ways (fasta in dataset files, through CLI argument, Web URL param, or Web "Customization" interface) does not exactly match (as in string comparison) the `.root_sequence.nuc` in Auspice JSON.
The warning is emitted:
- CLI: into console
- Web: into dev console, for every WebWorker "thread" (we don't currently have a good mechanism to display warnings int he app, especially the ones coming from Rust)
The warning message is the following. Please suggest improvements (paste a full quote into reply message or feel free to modify in the code).
<details>
<summary>Click to expand</summary>
> Nextclade detected that reference …
> feat: warn when standalone ref and tree ref don't match exactly

- packages/nextclade-web/src/components/GeneMap/GeneMap.tsx
The annotation visualization component were setting name of the CDS fragment as current CDS on click. This is incorrect: CDS name needs to be set instead (like it's done in the dropdown selector).
This lead to an error displayed in the peptide view when clicking on annotation viz and when name of CDS and CDS segment is different, which is always the case for Auspice datasets - Nextclade generates fragment names, as well as for multi-fragment CDSes.
Here I fix the problem by setting CDS name as current CDS on click, rather than fragment name.
> fix(web): error when selecting a cds fragment in annotation viz

- packages/nextclade/src/tree/tree_builder.rs
When new nodes are placed onto a ref node, sometimes we create an intermediate new node as a copy of the existing ref node. They are all named the same - `{node_key}_internal`. This is insufficient to provide uniqueness when multiple new nodes are placed onto the same ref node.
To address that, here I change names to also include query name and index.
> fix: prevent duplicate node names in output auspice json

- packages/nextclade-web/src/helpers/formatDate.ts
The bug is the inverted `.filter()` which filtered out all non-empty entries
> fix(web): correctly display 'updated at' time of datasets

- packages/nextclade-web/package.json
- packages/nextclade-web/src/pages/_app.tsx
- packages/nextclade-web/yarn.lock
This upgrades auspice [again](https://github.com/nextstrain/nextclade/releases/tag/3.7.3) to v2.55.0, while avoiding crash with error
```
choose-branch-labelling.js:116 Uncaught TypeError: (intermediate value).union is not a function
at Function.eval [as mapToProps] (choose-branch-labelling.js:116:73)
```
[here](https://github.com/nextstrain/auspice/blob/5afe5814b7304b65b3856df136ceeac88cf4690e/src/components/controls/choose-branch-labelling.js#L15-L16) due to `Set.union()` not available in older browsers ([caniuse](https://caniuse.com/mdn-javascript_builtins_set_union), [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/union))
The root of the problem, I think, was migration to Next.js 12 along with swc and removing babel. I am not sure if babel …
> feat: upgrade auspice and add polyfills

- packages/nextclade-cli/src/io/http_client.rs
Followup of https://github.com/nextstrain/nextclade/pull/1527
Adds a CLI arg with the same meaning as `NEXTCLADE_EXTRA_CA_CERTS` env var - to provide a path to extra CA certs. Perhaps some users might prefer a CLI arg. It was easy, so I thought why not?
> feat(cli): add --extra-ca-certs

- .github/workflows/cli.yml
Include hidden files since our sole path pattern is a hidden "file". Apparently this counts even though the files the pattern matches aren't hidden.
GitHub made this big breaking change of excluding hidden files without bumping the major version number of actions/upload-artifact.¹  It, rightfully so, caused a ruckus at the time and continues to be a gift that keeps on giving.
The only other actions/upload-artifacts usage, in
.github/workflows/web.yml, seemingly isn't affected even though the path contains a hidden directory.  Perhaps because in that case there are a few more directory components after it?
¹ <https://github.com/actions/upload-artifact/releases/tag/v4.4.0>
Resolves: <https://github.com/nextstrain/nextclade/issues/1532>
> fix(ci): Upload all CLI build outputs

- .github/workflows/cli.yml
- packages/nextclade/src/run/nextclade_run_one.rs
- tests/run-smoke-tests
NOTE: this PR targets branch `feat/qry-annotation` (PR #1578)
> feat: handle reverse-complemented sequences in gff and tbl output

- packages/nextclade/src/gene/cds_segment.rs
- packages/nextclade/src/gene/phase.rs
- packages/nextclade/src/io/genbank_tbl.rs
- packages/nextclade/src/run/nextclade_run_one.rs
Compared to bitflags:
Advantages:
- allows to store truncation amount
- requires no custom (de-)serialization code
Disadvantages:
- main logic is slightly more complex
> fix: allow truncation on both ends (enum version)
