nextstrain/nextclade

packages/web/src/algorithms/__tests__/alignPairwise.test.ts
packages/web/src/algorithms/alignPairwise.ts

This implements tests for the `pairwiseAlign` function. One test currently fails, which will require fixing the alignment function.

[WIP] Tests/alignment

---

packages/web/src/components/Layout/NavigationLogo.tsx
packages/web/src/components/Main/Title.tsx

feat: add beta badge

---

packages/web/src/components/About/AboutContent.mdx

fix: typos

---

packages/web/src/algorithms/parseSequences.ts

fix: make parser robust to various line delimiters and unexpected chracters

---

.github/workflows/codeql-analysis.yml

https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning

chore: setup Github CodeQL scanning

---

packages/web/src/components/Tree/Frequences.tsx
packages/web/src/components/Tree/Sidebar.tsx
packages/web/src/components/Tree/Tree.tsx
packages/web/src/components/Tree/TreePage.tsx
packages/web/src/types/auspice/src/components/entropy/index.d.ts
packages/web/tools/auspice-monkey-patch.sh

feat: add entropy panel

---

packages/web/src/components/Results/ButtonExport.tsx
packages/web/src/constants.ts
packages/web/src/io/serializeResults.ts
packages/web/src/state/algorithm/algorithm.actions.ts
packages/web/src/state/algorithm/algorithm.sagas.ts
packages/web/src/state/ui/ui.state.ts

feat: add export to tsv

---

packages/web/src/components/Common/List.tsx
packages/web/src/components/Results/Circle.tsx
packages/web/src/components/Results/ColumnName.tsx
packages/web/src/components/Results/ColumnNameTooltip.tsx
packages/web/src/components/Results/ColumnQCStatus.tsx
packages/web/src/components/Results/ListOfGaps.tsx
packages/web/src/components/Results/ListOfInsertions.tsx
packages/web/src/components/Results/ListOfMissing.tsx
packages/web/src/components/Results/ListOfMutations.tsx
packages/web/src/components/Results/ListOfNonACGTNs.tsx
packages/web/src/components/Results/ListOfQcIsuues.tsx
packages/web/src/components/Results/Tooltip.tsx
packages/web/src/components/Settings/SettingsButton.tsx
packages/web/src/helpers/formatInsertion.ts
packages/web/src/helpers/formatNonAcgtn.ts
packages/web/src/helpers/formatQCMixedSites.ts
packages/web/src/io/serializeResults.ts
packages/web/src/styles/components/Popover.scss

A mixture of small adjustments, important, but not worth opening separate PRs:
- properly format non-ACGTN ranges and insertion strings
- show per-rule QC icons in tooltips
- make tooltip more dense, remove QC from the main tooltip
- various small cosmetic tweaks

feat: pre release tweaks

---

packages/web/src/components/Results/Circle.tsx
packages/web/src/components/Results/ColumnQCStatus.tsx
packages/web/src/components/Results/ListOfQcIsuues.tsx

feat: make QC status icons' labels more distinct, single-letter

---

packages/web/src/algorithms/__tests__/alignPairwise.test.ts
packages/web/src/algorithms/alignPairwise.ts
packages/web/src/algorithms/run.ts
packages/web/src/cli/run.ts
packages/web/src/helpers/formatError.ts

fix: fix CLI crash on alignment failure

---

packages/web/src/algorithms/defaults/sars-cov-2/index.ts
packages/web/src/algorithms/defaults/viruses.ts
packages/web/src/algorithms/types.ts
packages/web/src/components/Main/MainPage.tsx

"Show me an example" link on main page was not loading the example sequences.
https://github.com/nextstrain/nextclade/pull/221#issuecomment-702011266
This PR fixes it.

fix: ensure example sequences are loading correctly

---

packages/web/src/components/Error/ErrorPopup.tsx

This adds a note to the user that some of the adblockers may interfere with the correct functioning of the application.

feat: warn about possible adblocker interference

---

packages/web/src/algorithms/tree/treeFindNearestNodes.ts

A follow-up of https://github.com/nextstrain/nextclade/pull/245 for private mutations counting.

feat: exclude gaps from private mutations counting

---

packages/web/src/algorithms/alignPairwise.ts
packages/web/src/algorithms/parseSequences.ts

EDIT(@ivan-aksamentov): Resolves https://github.com/nextstrain/nextclade/issues/288

feat: improve seed matching by logging good nucleotides

---

packages/web/src/components/About/AboutContent.mdx

Link is currently broken, fixes: https://github.com/nextstrain/nextclade/issues/300

Updated link for clade defining mutations

---

packages/nextalign/src/translate/extractGene.cpp
packages/nextalign/src/translate/extractGene.h
packages/nextalign/tests/extractGene.test.cpp

[nextalign] Correct gene extraction for incomplete sequences

---

packages/web/infra/lambda-at-edge/basicAuth.lambda.js

Resolves a few eslint warnings in AWS Lambda@Edge function

refactor: lint aws lambda function file

---

packages/web/src/components/About/AboutContent.mdx
packages/web/src/components/Layout/Footer.tsx
packages/web/src/components/Layout/LayoutMain.tsx
packages/web/src/components/Main/CladeSchema.tsx
packages/web/src/components/Main/MainSectionHero.tsx
packages/web/src/components/Main/MainSectionHeroControlsSimple.tsx
packages/web/src/components/Main/MainSectionHeroFeatures.tsx
packages/web/src/styles/components/Main.scss

This makes Nextclade look a bit better on mobile and fixes some minor styling issues here and there. Refer to commit messages for details.

fix: fix non-responsive elements on main page

---

packages/web/src/components/Main/CladeSchema.tsx

It is too large on large screens

feat: limit clade schema size

---

packages/nextalign/src/translate/extractGene.cpp

this PR fixes a problem in the gene extraction step where we checked for the gene length being a multiple of 3 before removing internal gaps.

Fix gene extraction

---

packages/web/src/components/Error/ErrorPopup.tsx
packages/web/src/state/algorithm/algorithmRun.sagas.ts

Now when there is an unrecoverable error during processing, the popup will appear displaying an error to the user

Show analysis errors to the user

---

packages/web/src/components/Error/ErrorPopup.tsx
packages/web/src/state/algorithm/algorithm.reducer.ts

This:
- fixes a problem when the error dialog cannot be dismissed
- adds a "Restart" button, which reloads the page
- applies small cosmetic improvements

Improve error dialog

---

packages/web/src/components/Results/HelpTips/HelpTipsColumnInsertions.mdx
packages/web/src/components/Results/ListOfInsertions.tsx
packages/web/src/helpers/formatInsertion.ts

- clarify insertion table heading text
- simplify insertions help dialog
As discussed in the internal Slack thread

Small improvements to insertions UI

---

data/sars-cov-2/qc.json
packages/nextclade/include/nextclade/nextclade.h
packages/nextclade/src/io/parseQcConfig.cpp
packages/nextclade/src/io/serializeQcConfig.cpp
packages/nextclade/src/qc/ruleStopCodons.cpp

Renames the new field to clarify intent

Rename knownStopCodons -> ignoredStopCodons

---

packages/nextclade/src/qc/ruleStopCodons.cpp

The check condition was inverted

Fix stop codons not being ignored

---

packages/nextalign_cli/docker/debian.dockerfile
packages/nextclade_cli/docker/debian.dockerfile

chore: add `ps` into debian docker images

---

packages/web/src/components/Main/DatasetSelectorDropdown.tsx

This fixes a bug where dataset selector does not switch datasets when selecting another dataset from the dropdown list.

fix: dataset selector does not switch datasets

---

packages/nextclade_common/src/datasets.cpp

This removes usage of the removed "description" filed in datasets. See https://github.com/nextstrain/nextclade_data/pull/8

feat: remove dataset descriptions

---

packages/web/src/components/SequenceView/PeptideContext.tsx

Reverts nextstrain/nextclade#555

Revert "fix: add missing keys for react component"

---

packages/nextclade/src/tree/findPrivateMutations.cpp

Here we filter out private substitutions and deletions from results, where positions fall into ranges with aminoacid X in query peptide.
In these cases the information is simply missing from the query and in the `processNodeMutations()` function if a substitution or a deletion is missing from query, but present in the node, a reversion is added to the results (a mutation from the node all the way to what was in the ref seq). We chose to remove these,
because we believe that a reversion is a less likely event and most of these are the sequencing errors followed by uncertainty in translation.
You can see the effect with position 417 here, which is no longer present in private substitutions of a branch:
Before:
After:

fix: don't add private reversions when query aa is unknown

---

.all-contributorsrc
README.md
packages/web/src/components/Team/TeamCredits.tsx
packages/web/src/components/Team/TeamCreditsMaintainer.tsx
packages/web/src/components/Team/TeamCreditsStyles.tsx

This PR:
Update after Richard's comment:

feat: add Cornelius as maintainer

---

packages/common/include/common/safe_string.h
packages/common/include/common/safe_string_view.h

This is only relevant for dev mode. I added some more checks to catch more illegal array accesses.

chore: add additional preconditions to safe strings

---

packages/nextclade/src/qc/ruleSnpClusters.cpp

Resolves https://github.com/nextstrain/nextclade/issues/707
Related to https://github.com/nextstrain/nextclade/pull/689
This tries to address the fact that reversions of deletions are now included into "all private mutations" array and so are processed in the "SNP clusters" QC rule.
Because sometimes reversions of deletions can come in large contiguous chunks, these mutations contribute to the cluster counts, making QC scores for some of the sequences worse. This was unexpected.
In order to mitigate this, it was decided in the team chat to exclude reversions of deletions from the consideration in the "SNP clusters" QC rule.
The technical implementation is to remove the intersection of "all private substotutions" and "reversions of deletions" from "all private substitutions". Implemented …

fix: exclude reversions of dels from consideration in "SNP clusters" QC

---

packages_rs/nextclade/src/align/insertions_strip.rs

fix: ensure last terminal insertion is stripped correctly

---

packages_rs/nextclade-web/package.json
packages_rs/nextclade-web/yarn.lock

https://github.com/nextstrain/auspice/blob/master/CHANGELOG.md#version-2372---20220527

chore(deps): bump auspice version to 2.37.2

---

packages_rs/nextclade-cli/src/dataset/dataset.rs
packages_rs/nextclade-cli/src/dataset/dataset_table.rs

Transition CLI to using `index_v2.json`
See the corresponding PR in data repo: https://github.com/nextstrain/nextclade_data/pull/26

feat(cli): use index_v2.json

---

packages_rs/nextclade-web/src/components/Results/ListOfInsertions.tsx

This is a port of 79e1f3b, which got lost during rust transition

fix(web): ensure truncated text is not repeated in insertions tooltip

---

packages_rs/nextclade/src/align/seed_alignment.rs

!!! This branch is based on https://github.com/nextstrain/nextclade/pull/838
This moves 2 variables along with the computation logic into the function, closer to the usage. These variables were not used anywhere outside the function.
Helped me to better understand the changes in https://github.com/nextstrain/nextclade/pull/838, and can perhaps allow to simplify logic in it.

refactor: move variables into the function to avoid extra arguments

---

packages_rs/nextclade-cli/src/dataset/dataset_table.rs

Small improvements in the looks of the table printed with `dataset list` and `dataset get` commands.

feat(cli): make dataset table prettier

---

packages_rs/nextclade/src/io/gff3.rs

feat(gff): accept locus_tag and gene in addition
warn if neither locus_tag nor gene_name present
This makes us accept the same gff that `augur translate` accepts, so to avoid config errors/duplication.
I also add warning if there are unexpected gene map entries. Erroring would be to extreme since we want genemaps to be able to contain unused fields. Just warn the user so they are aware.

feat(gff): accept locus_tag and gene in addition

---

packages_rs/nextclade-cli/src/cli/nextalign_cli.rs
packages_rs/nextclade-cli/src/cli/nextalign_loop.rs
packages_rs/nextclade-cli/src/cli/nextclade_cli.rs
packages_rs/nextclade-cli/src/cli/nextclade_loop.rs

feat(cli): improve error message when old, removed cli args are used

---

packages_rs/nextclade-cli/src/cli/nextalign_cli.rs
packages_rs/nextclade-cli/src/cli/nextclade_cli.rs

Adds extended description of input fasta positional argument: compression, multipl inputs, reading from stdin.
Adds information about compression to description of output arguments.

feat(cli): improve help messages for input fasta arg

---

packages_rs/nextclade/src/io/compression.rs

Related: https://github.com/nextstrain/nextclade/issues/888
This:
- `GZ_COMPRESSION`
- `BZ2_COMPRESSION`
- `XZ_COMPRESSION`
- `ZST_COMPRESSION`

feat(cli): make output compression faster

---

docs/user/algorithm/nextclade-pango.md

Noted in an email to our support address (ticket 510).

docs: fix typos

---

docs/user/output-files.md

- [docs: document limitations of JSON outputs](https://github.com/nextstrain/nextclade/commit/88238a8d4dd5907b08326e4fb6060c375d78ce1c)
- [docs: document output compression](https://github.com/nextstrain/nextclade/commit/5c73286a4e3200fa60c5f21d69c7ec2905a831d2)
- [docs: document how failed sequences are reflected in output files](https://github.com/nextstrain/nextclade/commit/cb569e5be0418eb74cf30c67d1cd4627f0e32e88)
<a href="https://user-images.githubusercontent.com/9403403/177962561-63ed5ba1-5de8-48d6-9e1f-514e835b652b.png">
<img
height="300px"
src="https://user-images.githubusercontent.com/9403403/177962561-63ed5ba1-5de8-48d6-9e1f-514e835b652b.png"
/>
</a>

docs: improve user dics for outputs

---

packages_rs/nextclade-web/src/io/fetchDatasetsIndex.ts

when the DATA_FULL_DOMAIN is started with '/', the HTTP Origin will
be added in front of it to make an absolute url.

Let user use relative url for nextclade datasets server.

---

docs/user/nextalign-cli.md
docs/user/nextclade-cli.md

Fixes a few errors in the CLI docs

docs: adjust cli docs to nextclade v2

---

packages_rs/nextclade-web/src/wasm/analyze.rs
packages_rs/nextclade-web/src/wasm/main.rs
packages_rs/nextclade/src/align/seed_alignment.rs
packages_rs/nextclade/src/io/compression.rs
packages_rs/nextclade/src/translate/translate_genes.rs
packages_rs/nextclade/src/tree/tree_preprocess.rs
packages_rs/nextclade/src/utils/collections.rs

This PR aims to:
- reduce amount of panics by replacing some of the calls to `.unwrap()` with proper error handling using `Result`
- improve error messages, especially in web app (where any panic leads to an error message "unreachable", without any details)

feat: improve error handling and error messages

---

CHANGELOG.md
packages_rs/nextclade/src/io/gff3.rs

This will check that genes in gene map have length divisible by 3

feat: validate gene length in gff3 parser

---

.github/workflows/bioconda.yml
.github/workflows/cli.yml

Update GitHub tokens

---

.github/workflows/builder-docker-image.yml
.github/workflows/cli.yml
.github/workflows/web.yml

Use new token and remove unnecessary encryption of username.
Part of org-level work in https://github.com/nextstrain/private/issues/73.

Update Docker Hub login

---

.github/workflows/cli.yml
docker-dev
tests/run-smoke-tests
tests/test-linux-distros

chore: run smoke tests with all available datasets

---

packages_rs/nextclade-web/public/manifest.json
packages_rs/nextclade-web/src/components/About/AboutContent.mdx
packages_rs/nextclade-web/src/constants.ts

This is to improve ranking in search engines

feat(web): add more relevant words to app description and main page text

---

packages_rs/nextclade-cli/src/cli/nextalign_loop.rs
packages_rs/nextclade-cli/src/cli/nextclade_loop.rs

Resolves https://github.com/nextstrain/nextclade/issues/491

feat(cli): improve error messages when reading ref sequence

---

packages_rs/nextclade/src/io/nextclade_csv.rs

Resolves: https://github.com/nextstrain/nextclade/issues/1036

fix: ensure alignment range conversion to 1-based

---

CHANGELOG.md
packages_rs/nextclade-web/.eslintrc.js
packages_rs/nextclade-web/config/next/next.config.ts
packages_rs/nextclade-web/src/pages/_document.tsx

Fix Google Search Console warnings

---

docs/dev/developer-guide.md

docs(dev): add dataset download command

---

packages_rs/nextclade-web/src/components/SequenceView/SequenceSelector.tsx

feat(web): visual improvements in genetic feature selector

---

packages_rs/nextclade/benches/bench_create_stripes.rs
packages_rs/nextclade/src/align/align.rs
packages_rs/nextclade/src/align/params.rs
packages_rs/nextclade/src/align/score_matrix.rs
packages_rs/nextclade/src/align/seed_alignment.rs
packages_rs/nextclade/src/align/seed_match2.rs
test_datasets/hiv/files/virus_properties.json
tests/run-smoke-tests

Resubmit of https://github.com/nextstrain/nextclade/pull/1212

Simpler chop

---

packages_rs/nextclade/src/align/seed_alignment.rs

During the 'rewind' step the amount by which the band is widened is increased if larger shifts between qry and ref are encountered going backwards. This widening was missing for the first (current) band which is dealt which outside of the rewind-loop.

fix: non-monotonous bands for stripe construction

---

packages_rs/nextclade/benches/bench_create_stripes.rs
packages_rs/nextclade/benches/bench_seed_alignment.rs
packages_rs/nextclade/src/align/align.rs
packages_rs/nextclade/src/align/params.rs
packages_rs/nextclade/src/align/seed_alignment.rs

Resubmit of #1232, rebased on top of #1231 to avoid difficult merges.
Added `max_band_area` CLI and dataset parameter.

feat: add max alignment band area check

---

packages_rs/nextclade/src/align/params.rs

Breaking change that requires simultaneous change in nextclade_data This makes all fields in pathogen.json camelCase for consistency
Linked PR https://github.com/nextstrain/nextclade_data/pull/85

feat(!): deserialize AlignmentPairwiseParams as camelCase

---

packages_rs/nextclade/src/io/dataset.rs

See: https://github.com/nextstrain/nextclade_data/pull/87

feat: remove updatedAt timestamp to avoid merge conflicts

---

packages_rs/nextclade/src/io/gff3.rs

https://en.wikipedia.org/wiki/Sequence_Ontology

refactor: it's sequence ontology not anthology

---

packages_rs/nextclade-web/src/components/Main/DatasetCurrent.tsx
packages_rs/nextclade-web/src/components/Main/DatasetCurrentSummary.tsx
packages_rs/nextclade-web/src/components/Main/DatasetSelector.tsx
packages_rs/nextclade-web/src/components/Main/MainInputForm.tsx
packages_rs/nextclade-web/src/components/Main/MainPage.tsx

A set of fixes and improvements for UI-5

UI-5 tweaks

---

packages_rs/nextclade-web/src/components/Tree/LogoPoweredByAuspice.tsx
packages_rs/nextclade-web/src/components/Tree/TreePageContent.tsx
packages_rs/nextclade-web/src/types/auspice/src/components/main/styles.d.ts

Apply theme from nextstrain.org customizations to Auspice sidebar on tree page

Apply nextstrain.org sidebar theme

---

packages_rs/nextclade-web/src/components/Export/ExportTabColumnConfig.tsx
packages_rs/nextclade-web/src/components/Export/ExportTabMain.tsx
packages_rs/nextclade-web/src/hooks/useExportResults.ts

https://github.com/nextstrain/nextclade/assets/9403403/586b4902-a627-4b72-a2ee-5eb5a37daa68

feat(web): add progress indicators to export buttons

---

packages_rs/nextclade-web/src/components/Main/QuerySequenceList.tsx

feat(web): prettify query sequence file list

---

packages_rs/nextclade-web/src/components/Export/ExportTabColumnConfig.tsx

Followup of #1358
https://github.com/nextstrain/nextclade/assets/9403403/39adca41-6144-46bd-ae60-41e716cfd7c0

feat(web): add progress indicators to export buttons on column config page

---

packages_rs/nextclade-web/src/components/Common/BrowserWarning.tsx

Resolves https://github.com/nextstrain/nextclade/issues/1350

feat(web): improve 'Unsupported browser' warning

---

packages_rs/nextclade-web/src/components/Link/Link.tsx
packages_rs/nextclade-web/src/components/Main/DatasetCurrentSummary.tsx
packages_rs/nextclade-web/src/components/Main/DatasetCustomizationIndicator.tsx
packages_rs/nextclade-web/src/state/inputs.state.ts

feat(web): add dataset customization indicator to main page

---

packages/nextclade-web/src/components/Main/MainInputForm.tsx

Autosuggestion will not run (ever) automatically when navigating to `/datasets` page

feat(web): don't run dataset suggestion when navigating to datasets page

---

packages/nextclade/src/io/concat.rs
packages/nextclade/src/io/fasta.rs

Resolves https://github.com/nextstrain/nextclade/issues/1422
`FastaReader` throws an error if there's a leading newline in the inputs.
Because of the changes in `Concat` iterator in Nextclade v3, `FastaReader` now receives additional newlines, which `Concat` inserts between input readers (e.g. files or string streams). This was a necessary fix to ensure that there's a separation between two concatenated readers when the previous reader does not end with a newline. However, now if the first reader (or the only reader)  is empty or reads only newlines, then after `Concat` `FastaReader` receives only a `\n` characters, which it could not interpret and fails with an error. This is a change of behavior compared to Nextclade v2.
In the new version I make sure to skip the leading newlines. The …

fix: handle leading newlines in fasta parser correctly 

---

packages/nextclade-web/src/components/Main/DatasetInfo.tsx

https://github.com/nextstrain/nextclade/issues/1437

fix(web): attempt to remove vertical scrollbars in dataset  names

---

docs/dev/developer-guide.md

Updates developer guide to replace deprecated option with supported one. 
#1451

Change output-dir to output-all

---

packages/nextclade-cli/src/cli/nextclade_cli.rs

Followup of: https://github.com/nextstrain/nextclade/pull/1455

feat(cli): add Auspice JSON to CLI help and docs for `--input-dataset`

---

packages/nextclade-web/src/io/fetchSingleDatasetAuspice.ts

fix(web): prefer name from pathogen info rather than from Auspice meta

---

packages/nextclade-web/src/mdx-components.tsx
packages/nextclade-web/src/styles/global.scss

Resolves https://github.com/nextstrain/nextclade/issues/1487

fix(web): styling of details  & summary in markdown content

---

packages/nextclade-web/src/components/SequenceView/SequenceMarkerFrameShift.tsx
packages/nextclade-web/src/components/SequenceView/SequenceMarkerInsertion.tsx
packages/nextclade-web/src/components/Settings/SeqViewSettings.tsx
packages/nextclade-web/src/state/seqViewSettings.state.ts

Resolves https://github.com/nextstrain/nextclade/issues/1477

feat(web): add toggles for insertions and frame shifts markers
